graph TD
  AcessoSeesaw --> Pessoa
  AnamnesePessoa --> Pessoa
  AnamnesePessoaResposta --> AnamnesePessoa
  AnamnesePessoaResposta --> AnamnesePessoaResposta
  AnamnesePessoaRespostaOpcao --> AnamnesePessoaResposta
  AtendimentoEspecialistaPessoa --> EspecialistaPessoa
  AtendimentoPessoa --> Pessoa
  ConteudoOnlinePerfil --> PerfilAcesso
  EspecialistaPessoa --> AnamnesePessoaResposta
  EspecialistaPessoa --> Pessoa
  ExcecoesDeAcesso --> PerfilAcesso
  FotoPessoa --> Pessoa
  GrupoPerguntaPerfilAcesso --> PerfilAcesso
  LIV_ImportacaoDadosLinhasUsuario --> PerfilAcesso
  LIV_PerfilAcessoAcaoMarketing --> PerfilAcesso
  LIV_PerfilAcessoMaterial --> PerfilAcesso
  LIV_PerfilAcessoNoticia --> PerfilAcesso
  LogAcessoPlataformaAdaptativa --> LogAcessoProduto
  LogAcessoProduto --> LogAcesso
  LogUpdateDadosPessoais --> Pessoa
  LogUpdateFotoPessoa --> Pessoa
  PerfilAcessoFuncionalidade --> PerfilAcesso
  PerfilAcessoTipoRede --> PerfilAcesso
  PerfilDeAcessoDoUsuario --> PerfilAcesso
  PesquisaSatisfacaoUsuario --> PerfilAcesso
  PesquisaSatisfacaoUsuario --> Pessoa
  Pessoa --> Pessoa
  PessoaAprovadaConselho --> Pessoa
  PessoaDadosAlterados --> Pessoa
  PessoaDePara --> Pessoa
  PessoaDocumento --> Pessoa
  PessoaRedeEmail --> Pessoa
  PessoaSegmento --> Pessoa
  PessoaTelefone --> Pessoa
  POAPessoa --> Pessoa
  ProdutoPermissao --> PerfilAcesso
  ProfessorPerfilVigente --> Pessoa
  ProfessorPerfilVigente --> PessoaTelefone
  ServicoPerfilAcesso --> PerfilAcesso
  TermosDeUsoRedePerfil --> PerfilAcesso
  Usuario --> Pessoa
  UsuarioLinha --> Usuario
  UsuarioUltimoFiltro --> UsuarioUltimoFiltro
  BaseDeAcessos
  BaseDeUsuariosParaMarketing
  ConfiguracaoGlobalUsuario
  FalhaLogin
  LIV_LOG_Acessos
  LIV_NotificacaoUsuario
  LIV_UsuarioInativo
  LIV_UsuarioSegmento
  LIV_WebinarPerfilAcesso
  LogAcessoResultadoBimestral
  LogAcessoTipo
  LogInconsistenciaImportacaoPedidoEditora
  POAPessoa_Modulo
  PerfilAcessoFuncionalidadeSegmentoAgrupamento
  PermissaoCartaoCredito
  PermissaoDW
  PesquisaOpiniaoUsuario
  PesquisaPublicoPerfilAcesso
  PesquisaResultadoPerfilAcesso
  PessoaEndereco
  PessoaJuridica
  RedeAcesso
  RelatorioAcessoFinanceiro
  TempLogUpdateUsuario
  UsuarioAcesso
  UsuarioAcessoGuia
  UsuarioAcessoGuiaFinanceiro
  UsuarioAuthToken
  UsuarioFuncionalidade
  UsuarioLIV
  UsuarioLIVConteudoLIV
  UsuarioLogarComo
  UsuarioProdutoDestaque
  UsuarioRede
  UsuarioSismat
  UsuarioVisualizouCampanha
  UsuarioVisualizouRegraPLAD
  Usuario_Origem
  Usuario_id_origem
  UsuariosNotificacaoEnvioCartao
  bkp_email_usuario
  temp_BasicAcessouUltimosMeses
