graph TD
  AlunoAvaliacaoPresenca --> Chamada
  AlunoAvaliacaoPresenca --> TipoPresenca
  AlunoFalta --> TipoPresenca
  AlunoFrequencia --> TipoFrequencia
  Aula_LancamentoComportamento --> LancamentoComportamento
  AulaEvento --> TipoAulaEvento
  AulaEventoAnotacoes --> AulaEvento
  AulaEventoDeverDeCasa --> AulaEvento
  AulaEventoPauta --> AulaEvento
  AulaOnline --> TipoAulaOnline
  AulaOnline --> AulaOnline
  AulaOnlineAcesso --> AulaOnline
  AulaOnlineAcessoPing --> AulaOnlineAcesso
  DiaSemAulaMotivo --> DiaSemAulaTipo
  DiaSemAulaTurma --> DiaSemAulaMotivo
  FrequenciaProfessor --> FrequenciaProfessor
  FrequenciaProfessor --> MotivoFrequenciaProfessorTipoPresenca
  FrequenciaProfessorSubstituto --> FrequenciaProfessor
  FuncionalidadeTipoPresenca --> TipoPresenca
  HistoricoHoraAulaPgto --> HoraAulaPgto
  HistoricoHoraAulaSegmentoPgto --> HoraAulaSegmentoPgto
  HoraAulaPgto --> TipoHoraAula
  HoraAulaSegmentoPgto --> TipoHoraAula
  LancamentoNotasBusca --> Chamada
  LancamentoNotasStatusPorTurma --> Chamada
  LIV_FeedbackAula --> LIV_FeedbackCadastroAulas
  LIV_FeedbackAulaRespostas --> LIV_FeedbackAula
  MonitoriaMonitorPresenca --> TipoAbonoFalta
  MonitoriaMonitorPresenca --> TipoPresenca
  MotivoFrequenciaProfessor --> MotivoFrequenciaProfessor
  MotivoFrequenciaProfessorTipoPresenca --> MotivoFrequenciaProfessor
  MotivoFrequenciaProfessorTipoPresenca --> TipoPresenca
  ProtocoloLancamento --> Chamada
  ProtocoloLancamentoAluno --> ProtocoloLancamento
  ProtocoloLancamentoAluno --> ProtocoloLancamentoStatus
  ProtocoloLancamentoBusca --> Chamada
  TipoAulaOnlineRede --> TipoAulaOnline
  TipoAulaOnlineRedeSerie --> TipoAulaOnline
  AlunoAvaliacaoPresenca_bkp
  AlunoAvaliacaoPresenca_bkp2
  AlunoFaltas
  AlunoJustificativaFalta
  AulaEventoConfiguracao
  AulaEventoPautaMensal
  AulaEventoPautaSemanal
  AulaEventoUltimaAlteracao
  Aula_ComentarioComportamento
  BaseDeLancamentoNotas
  DiaSemAula
  DuracaoTempoAula
  HoraAulaPadrao
  ImportacaoFrequencia
  LIV_MaterialPlanoAula
  LIV_StatusPlanoAula
  LogAulaOnlineAssistida
  POANaoPossuiAula
  POANaoPossuiAula_Modulo
  PercentualFrequencia
  PercentualFrequenciaLog
  PeriodoLancamentoFrequenciaProfessor
  ProdutoLancamentoNota
  RelatorioLancamentoNotasEscolaEleva
  RelatorioLancamentoPresencas
  RelatorioPresencaEE
  RelatorioPresencaEmSimulados
  StatusLancamentoFrequencia
  TempoAula
  TipoChamada
