graph TD
  AcessoSeesaw --> AnoLetivo
  AcessoSeesaw --> Pessoa
  AdminEscola --> Escola
  AdminEscola --> Pessoa
  AdminEscola --> Rede
  AdminEscola --> Segmento
  Agendamento --> ServicoAgendado
  Agrupamento --> Agrupamento
  AgrupamentoLegendaRedacao --> LegendaRedacao
  AgrupamentoLegendaRedacao --> Agrupamento
  AlocacaoCorretor --> PessoaEscolaAcesso
  AlocacaoCorretor --> Usuario
  AlocacaoFolha --> DisciplinaFolha
  AlocacaoFolha --> MotivosSaida
  AlocacaoFolha --> PessoaEscolaAcesso
  AlocacaoFolha --> Turma
  AlocacaoFolhaLicenca --> AlocacaoFolha
  AlocacaoFolhaLicenca --> MotivosSaida
  AlocacaoFolhaLicenca --> PessoaEscolaAcesso
  AlocacaoFolhaLicenca --> ProfessorLicenca
  AlocacaoProfessores --> AlocacaoProfessoresEtapa
  AlocacaoProfessores --> AnoLetivo
  AlocacaoProfessores --> Rede
  AlocacaoProfessoresLinha --> AlocacaoProfessores
  AlocacaoProfessoresLinha --> Disciplina
  AlocacaoProfessoresLinha --> Escola
  AlocacaoProfessoresLinha --> ProfessorPerfilVigente
  AlocacaoProfessoresLinha --> Turma
  AlocacaoRede --> Rede
  AlunoAP --> AnoLetivo
  AlunoAP --> Pessoa
  AlunoAtendimento --> AlunoEscola
  AlunoAtendimento --> MotivoAtendimento
  AlunoAvaliacaoPresenca --> Avaliacao
  AlunoAvaliacaoPresenca --> Chamada
  AlunoAvaliacaoPresenca --> Pessoa
  AlunoAvaliacaoPresenca --> TipoPresenca
  AlunoCartao --> EnvioLeituraCartao
  AlunoCartao --> Pessoa
  AlunoCartao --> ProvaCodigo
  AlunoCartao --> AnoLetivo
  AlunoCartao --> Rede
  AlunoCartaoLinha --> AlunoCartao
  AlunoCartaoNota --> AlunoCartao
  AlunoCartaoNota --> Avaliacao
  AlunoCartaoNota --> Chamada
  AlunoCartaoNota --> AlunoCartaoNota
  AlunoConselhoClasse --> Avaliacao
  AlunoConselhoClasse --> Pessoa
  AlunoEletiva --> AnoLetivo
  AlunoEletiva --> Rede
  AlunoEletivaLinha --> AlunoEletiva
  AlunoEscola --> FotoPessoa
  AlunoEscola --> PessoaEscolaAcesso
  AlunoEscola --> Pessoa
  AlunoEscola --> TipoSaidaAluno
  AlunoEscola --> Turma
  AlunoEscolaDependencia --> AlunoEscola
  AlunoEscolaDependencia --> Disciplina
  AlunoEscolaDisciplina --> Disciplina
  AlunoEscolaDisciplina --> AlunoEscola
  AlunoEscolaDisciplina --> ItinerarioFormativoCiclo
  AlunoEscolaDisciplina --> ItinerarioFormativoPeriodo
  AlunoEscolaDisciplinaComportamento --> AlunoEscola
  AlunoEscolaDisciplinaComportamento --> Disciplina
  AlunoEscolaDisciplinaComportamento --> TipoComportamentoAluno
  AlunoEscolaEletiva --> AlunoEscola
  AlunoEscolaEletiva --> Disciplina
  AlunoEscolaEletiva --> SemestreEletiva
  AlunoEscolaItinerarioFormativo --> AlunoEscola
  AlunoEscolaItinerarioFormativo --> ItinerarioFormativo
  AlunoEscolaItinerarioFormativo --> ItinerarioFormativoOferta
  AlunoEscolaLinguaEstrangeira --> AlunoEscola
  AlunoEscolaLinguaEstrangeira --> Disciplina
  AlunoEscolaResponsavel --> AlunoEscola
  AlunoEscolaResponsavel --> Pessoa
  AlunoExecucaoProva --> AlunoProva
  AlunoExecucaoProva --> ProvaSituacao
  AlunoFalta --> Pessoa
  AlunoFalta --> TipoPresenca
  AlunoFaltas --> Avaliacao
  AlunoFaltas --> Pessoa
  AlunoFrequencia --> Escola
  AlunoFrequencia --> Pessoa
  AlunoFrequencia --> TipoFrequencia
  AlunoFrequencia --> Turno
  AlunoJustificativaFalta --> Pessoa
  AlunoLaudoMedico --> Pessoa
  AlunoNecessidadesEspeciais --> Pessoa
  AlunoNecessidadesEspeciaisRelatorio --> Agrupamento
  AlunoNecessidadesEspeciaisRelatorio --> AnoLetivo
  AlunoNecessidadesEspeciaisRelatorio --> Pessoa
  AlunoNota --> TipoJustificativaNota
  AlunoNota --> Avaliacao
  AlunoNota --> Chamada
  AlunoNota --> TipoNotaFormativa
  AlunoNota --> ProdutoLancamentoNota
  AlunoNota --> Pessoa
  AlunoNota --> Situacao
  AlunoNota --> AnoLetivo
  AlunoNota --> Rede
  AlunoNotaDetalhamento --> Avaliacao
  AlunoNotaDetalhamento --> Pessoa
  AlunoNotaLinha --> AlunoNota
  AlunoNotaRecomendacao --> Avaliacao
  AlunoNotaRecomendacao --> Pessoa
  AlunoNotaTRI --> Avaliacao
  AlunoNotaTRI --> Pessoa
  AlunoOcorrencia --> AlunoEscola
  AlunoOcorrencia --> Ocorrencia
  AlunoParentesco --> AlunoEscola
  AlunoParentesco --> TipoParentesco
  AlunoProva --> AvaliacaoFormativa
  AlunoProva --> Pessoa
  AlunoProva --> ProvaSituacao
  AlunoProvaResposta --> AlunoProva
  AlunoProvaResposta --> QuestaoRespostaObjetiva
  AlunoSemNecessidadesEspeciais --> Pessoa
  AlunoTendencia --> Ciclo
  AlunoTendencia --> Disciplina
  AlunoTendencia --> Pessoa
  AlunoTendencia --> Turma
  AnamnesePessoa --> Pessoa
  AnamnesePessoa --> VersaoAnamnese
  AnamnesePessoaResposta --> AnamnesePessoa
  AnamnesePessoaResposta --> AnamnesePessoaResposta
  AnamnesePessoaResposta --> PerguntaVersaoAnamnese
  AnamnesePessoaResposta --> AlunoEscola
  AnamnesePessoaRespostaOpcao --> AnamnesePessoaResposta
  AnamnesePessoaRespostaOpcao --> Disciplina
  AnamnesePessoaRespostaOpcao --> OpcaoResposta
  AnoLetivoProduto --> AnoLetivo
  AnoLetivoProduto --> Produto
  AnoLetivoSemanas --> AnoLetivo
  Anotacao --> Redacao
  AnotacaoLegendaRedacao --> LegendaRedacao
  AnotacaoLegendaRedacao --> Competencia
  AnotacaoLegendaRedacao --> Anotacao
  AnotacaoRegraGeralRedacao --> RegraGeralRedacao
  AnotacaoRegraGeralRedacao --> Anotacao
  AoVivoSerie --> Serie
  Assunto --> Disciplina
  Atendimento --> AlunoEscola
  Atendimento --> MotivoAtendimento
  Atendimento --> SolicitanteAtendimento
  Atendimento --> TipoPublicoAtendido
  AtendimentoAvaliacao --> AtendimentoEnfermaria
  AtendimentoAvaliacaoItem --> AtendimentoAvaliacao
  AtendimentoAvaliacaoItem --> Avaliacao
  AtendimentoEnfermaria --> AlunoEscola
  AtendimentoEnfermaria --> EscolaSerieDisciplina
  AtendimentoEnfermaria --> Pessoa
  AtendimentoEnfermaria --> TipoDeIntervalo
  AtendimentoEscolaEleva --> Pessoa
  AtendimentoEscolaEleva --> TipoAtendimentoEscolaEleva
  AtendimentoEspecialistaPessoa --> EspecialistaPessoa
  AtendimentoPessoa --> Atendimento
  AtendimentoPessoa --> Pessoa
  AtendimentoProcedimentoEnfermagem --> AtendimentoEnfermaria
  AtendimentoProcedimentoEnfermagemItem --> AtendimentoProcedimentoEnfermagem
  AtendimentoProcedimentoEnfermagemItem --> ProcedimentoEnfermagem
  AtendimentoProcedimentoEnfermagemItemMedicamentoFormato --> AtendimentoProcedimentoEnfermagemItem
  AtendimentoProcedimentoEnfermagemItemMedicamentoFormato --> MedicamentoFormato
  AtendimentoRegistroEnfermagem --> AtendimentoEnfermaria
  AtendimentoResultadoFinal --> AtendimentoEnfermaria
  AtendimentoSV --> AtendimentoEnfermaria
  Atualidade --> Assunto
  Atualidade --> Conteudo
  AtualidadeLinkRelacionado --> Atualidade
  AtualidadeRedeEscola --> Atualidade
  AtualidadeRedeEscola --> Escola
  AtualidadeRedeEscola --> Rede
  AtualidadeSerie --> Atualidade
  AtualidadeSerie --> Serie
  AtualidadeTurma --> Atualidade
  AtualidadeTurma --> Turma
  Aula_ComentarioComportamento --> ComentarioComportamento
  Aula_ComentarioComportamento --> Disciplina
  Aula_ComentarioComportamento --> Pessoa
  Aula_ComentarioComportamento --> Turma
  Aula_LancamentoComportamento --> Disciplina
  Aula_LancamentoComportamento --> LancamentoComportamento
  Aula_LancamentoComportamento --> Pessoa
  Aula_LancamentoComportamento --> TipoComportamento
  Aula_LancamentoComportamento --> Turma
  AulaEvento --> DiaLetivoExtra
  AulaEvento --> Disciplina
  AulaEvento --> TipoAulaEvento
  AulaEvento --> Turma
  AulaEvento --> TurmaTempo
  AulaEvento --> Turno
  AulaEventoAnotacoes --> AulaEvento
  AulaEventoConfiguracao --> AnoLetivo
  AulaEventoConfiguracao --> Rede
  AulaEventoDeverDeCasa --> AulaEvento
  AulaEventoPauta --> AulaEvento
  AulaEventoPautaMensal --> Disciplina
  AulaEventoPautaMensal --> Turma
  AulaEventoPautaSemanal --> Disciplina
  AulaEventoPautaSemanal --> Turma
  AulaEventoUltimaAlteracao --> Turma
  AulaOnline --> TipoAulaOnline
  AulaOnline --> AulaOnline
  AulaOnlineAcesso --> AulaOnline
  AulaOnlineAcesso --> PerfilDeAcessoDoUsuario
  AulaOnlineAcesso --> PessoaEscolaAcesso
  AulaOnlineAcessoPing --> AulaOnlineAcesso
  AutorSegmentoDisciplina --> Disciplina
  AutorSegmentoDisciplina --> PerfilDeAcessoDoUsuario
  AutorSegmentoDisciplina --> Segmento
  Avaliacao --> Agrupamento
  Avaliacao --> AreaConhecimento
  Avaliacao --> Ciclo
  Avaliacao --> Disciplina
  Avaliacao --> Conteudo
  Avaliacao --> EstruturaAvaliacaoImportacaoEstrutura
  Avaliacao --> Avaliacao
  Avaliacao --> TipoAvaliacao
  Avaliacao --> TipoDivisaoEscola
  Avaliacao --> TipoResultado
  AvaliacaoDisciplina --> Avaliacao
  AvaliacaoDisciplina --> Disciplina
  AvaliacaoEditora --> Disciplina
  AvaliacaoEditora --> ProvaEditora
  AvaliacaoEditora --> TipoQuestao
  AvaliacaoEscola --> Avaliacao
  AvaliacaoEscola --> Escola
  AvaliacaoEscolaEleva --> Avaliacao
  AvaliacaoEscolaEleva --> Classroom
  AvaliacaoEscolaEleva --> Disciplina
  AvaliacaoEscolaTurma --> AvaliacaoEscolaTurmaStatus
  AvaliacaoEscolaTurma --> AvaliacaoFormativa
  AvaliacaoEscolaTurma --> Escola
  AvaliacaoEscolaTurma --> Rede
  AvaliacaoEscolaTurma --> Serie
  AvaliacaoEscolaTurma --> Turma
  AvaliacaoFormativaDisciplina --> AvaliacaoFormativa
  AvaliacaoFormativaDisciplina --> Disciplina
  AvaliacaoFormativaEscola --> AvaliacaoFormativa
  AvaliacaoFormativaEscola --> Escola
  AvaliacaoFormativaMarcaPublico --> AvaliacaoFormativa
  AvaliacaoFormativaMarcaPublico --> Marca
  AvaliacaoFormativaMarcaPublico --> Segmento
  AvaliacaoFormativaMarcaPublico --> Serie
  AvaliacaoFormativaProva --> AvaliacaoFormativa
  AvaliacaoFormativaProva --> Prova
  AvaliacaoFormativaPublico --> AvaliacaoFormativa
  AvaliacaoFormativaPublico --> Rede
  AvaliacaoFormativaPublico --> Segmento
  AvaliacaoFormativaPublico --> Serie
  AvaliacaoFormativaQuestoes --> AvaliacaoFormativa
  AvaliacaoFormativaQuestoes --> Questao
  AvaliacaoMediaAvaliacao --> Avaliacao
  AvaliacaoModelo --> Disciplina
  AvaliacaoModelo --> Conteudo
  AvaliacaoModelo --> ProvaModelo
  AvaliacaoModelo --> StatusAvaliacaoModelo
  AvaliacaoModelo --> TipoQuestao
  AvaliacaoModeloChat --> AvaliacaoModelo
  AvaliacaoModeloChat --> PerfilAcesso
  AvaliacaoModeloHistorico --> AvaliacaoModelo
  AvaliacaoModeloHistorico --> StatusAvaliacaoModelo
  AvaliacaoModeloQuestao --> AvaliacaoModelo
  AvaliacaoModeloQuestao --> Questao
  AvaliacaoSerie --> Avaliacao
  AvaliacaoSerie --> Escola
  AvaliacaoSerie --> Serie
  BaseDeAvaliacoesAluno --> BaseDeAlunos
  BaseDeAvaliacoesAluno --> BaseDeAvaliacoes
  BaseDeDatasFeriados --> BaseDeDatas
  BaseDeDatasFeriados --> Cidade
  BloqueioBoletim --> Ciclo
  BloqueioBoletim --> TipoAvaliacao
  BloqueioBoletim --> Turma
  BloqueioMaterialComplementar --> Agrupamento
  BloqueioMaterialComplementar --> ConteudoOnline
  BloqueioMaterialComplementar --> Disciplina
  BloqueioMaterialComplementar --> Escola
  BloqueioMaterialComplementar --> Rede
  BoletimEscolaEleva --> Pessoa
  BoletimEscolaEleva --> Ciclo
  BonusCriterio --> AnoLetivo
  BonusCriterioPublico --> BonusCriterio
  BonusCriterioPublico --> Etapa
  BonusCriterioPublico --> Rede
  BonusCriterioPublico --> Segmento
  BonusCriterioPublicoFaixa --> BonusCriterioPublico
  BonusCriterioPublicoVolume --> BonusCriterioPublico
  BonusCriterioPublicoVolume --> Ciclo
  BonusPlataformaAdaptativa --> BaseDeAlunos
  BuscaQuery --> Usuario
  CadernoResultadosLiberacao --> Escola
  CadernoResultadosLiberacao --> Prova
  CadernoResultadosMedia --> Avaliacao
  CadernoResultadosMedia --> CadernoResultadosLiberacao
  CaixaDeSaidaDeEmail --> Usuario
  CaixaDeSaidaDeEmail --> EstadoEnvio
  CaixaDeSaidaDeEmail --> Produto
  CalendarioEvento --> Avaliacao
  CalendarioEvento --> CalendarioEventoRecorrencia
  CalendarioEvento --> CalendarioGrupo
  CalendarioEvento --> Disciplina
  CalendarioEvento --> PessoaEscolaAcesso
  CalendarioEvento --> TipoAtividadeAgenda
  CalendarioEventoAluno --> CalendarioEvento
  CalendarioEventoRecorrencia --> CalendarioTipoRecorrencia
  CalendarioGrupo --> Rede
  CalendarioGrupo --> Serie
  CalendarioGrupo --> TipoAtividadeAgenda
  CalendarioGrupo --> Turma
  CalendarioGrupo --> Turno
  CampanhaPermissoes --> Campanha
  CampanhaPermissoes --> Escola
  CampanhaPermissoes --> PerfilAcesso
  CampanhaPermissoes --> Segmento
  CampanhaPermissoes --> Serie
  CampanhaPermissoes --> Rede
  CampoDinamicoListaEspecifica --> CampoDinamico
  CanalChatBotConectado --> AlunoEscola
  CandidatoBolsao --> AnoLetivo
  CandidatoBolsao --> Escola
  CandidatoBolsao --> PessoaEscolaAcesso
  CandidatoBolsao --> Serie
  CargaDisciplinaAlteracao --> MotivosSaida
  CargaDisciplinaAlteracao --> TurmaDisciplina
  CargaHoraria --> Disciplina
  CargaHoraria --> EscolaSerie
  CargaHoraria --> RedeSerie
  CargaHoraria --> AnoLetivo
  CargaHoraria --> Rede
  CargaHorariaLinha --> CargaHoraria
  CargaProfessorEntrando --> CargaDisciplinaAlteracao
  CargaProfessorEntrando --> PessoaEscolaAcesso
  CargaProfessorSaindo --> CargaDisciplinaAlteracao
  CargaProfessorSaindo --> PessoaEscolaAcesso
  CargoPagamentoCargo --> Cargo
  CargoPagamentoCargo --> CargoPagamento
  Cartao --> ProfessorTurmaDisciplina
  Cartao --> RedeQuesito
  Cartao --> Turma
  CartaoResposta --> Cartao
  CartaoResposta --> RedeOpcao
  ChamadoOtrsTicket --> ChamadoOtrsTipo
  ChamadoOtrsTicket --> Escola
  ChamadoOtrsTicket --> Rede
  ChamadoOtrsTipo --> ChamadoOtrsFila
  ChamadoOtrsTipo --> ChamadoOtrsSLA
  ChamadoOtrsTipo --> ChamadoOtrsTipo
  ChamadoOtrsTipo --> Rede
  ChamadoOtrsTipoCampo --> ChamadoOtrsCampo
  ChamadoOtrsTipoCampo --> ChamadoOtrsTipo
  Ciclo --> Etapa
  Ciclo --> Ciclo
  CicloDeMatriculas --> Rede
  Cidade --> Estado
  ClasseExemplo --> AnoLetivo
  ClasseExemplo --> Rede
  ClasseExemploEscola --> ClasseExemplo
  ClasseExemploEscola --> Escola
  ClassePagamento --> RedePagamento
  ClasseTurmaSegmentoPgto --> ClassePgto
  ClasseTurmaSegmentoPgto --> SegmentoPgto
  ClasseTurmaSegmentoPgto --> Turma
  Classroom --> Disciplina
  Classroom --> Turma
  ClassroomAluno --> Classroom
  ClassroomBoletim --> Ciclo
  ClassroomBoletim --> Classroom
  ClassroomBoletim --> Disciplina
  ClassroomCoordenador --> Classroom
  ClassroomProfessor --> Classroom
  Colaborador --> Cargo
  Colaborador --> Pessoa
  ColecaoComercial --> AnoLetivo
  ColecaoComercial --> Serie
  ColecaoComercialEscola --> ColecaoComercial
  ColecaoComercialEscola --> Escola
  ComentarioComportamento --> Disciplina
  ComentarioComportamento --> Pessoa
  ComentarioComportamento --> Turma
  ComentarioRedacao --> LegendaRedacao
  ComentarioRedacao --> Redacao
  CompetenciaAgrupamento --> Agrupamento
  CompetenciaAgrupamento --> Competencia
  ComunicadoCanalEnvio --> CanalEnvio
  ComunicadoCanalEnvio --> Comunicado
  ComunicadoEscolaSerieTurma --> Comunicado
  ComunicadoEscolaSerieTurma --> Escola
  ComunicadoEscolaSerieTurma --> Rede
  ComunicadoEscolaSerieTurma --> Serie
  ComunicadoEscolaSerieTurma --> Turma
  ComunicadoImagem --> Comunicado
  ComunicadoImagem --> Usuario
  ComunicadoLogEnvio --> ComunicadoCanalEnvio
  ComunicadoLogEnvio --> EstadoEnvio
  ComunicadoLogEnvioHistorico --> ComunicadoCanalEnvio
  ComunicadoLogEnvioHistorico --> EstadoEnvio
  ComunicadoMobile --> Comunicado
  ComunicadoMobileEscolaSerieTurma --> AlunoEscola
  ComunicadoMobileEscolaSerieTurma --> ComunicadoMobile
  ComunicadoMobileEscolaSerieTurma --> Escola
  ComunicadoMobileEscolaSerieTurma --> Rede
  ComunicadoMobileEscolaSerieTurma --> Serie
  ComunicadoMobileEscolaSerieTurma --> Turma
  ComunicadoMobileLido --> Comunicado
  ComunicadoPublico --> Comunicado
  ComunicadoPublico --> PerfilAcesso
  ComunicadoTemplate --> Rede
  ConfiguracaoPeriodoLetivo --> EscolaSerie
  ConfiguracaoPeriodoLetivo --> TipoChamada
  ConfiguracaoTempoPadrao --> EscolaSerie
  ConfiguracaoTempoPadrao --> Turno
  ConselhoClasse --> AnoLetivo
  ConselhoClasse --> Rede
  ConselhoClassePublico --> ConselhoClasse
  ConselhoClassePublico --> Escola
  ConselhoClassePublico --> EstruturaAvaliacao
  ConselhoClassePublico --> Serie
  ConselhoClassePublicoFaixa --> ConselhoClassePublico
  Conteudo --> TipoArquivo
  ConteudoOnline --> Agrupamento
  ConteudoOnline --> AnoLetivo
  ConteudoOnline --> ConteudoOnlineExtensao
  ConteudoOnline --> ConteudoOnlineTipo
  ConteudoOnline --> Disciplina
  ConteudoOnline --> Rede
  ConteudoOnline --> TipoRede
  ConteudoOnlineEscola --> ConteudoOnline
  ConteudoOnlineEscola --> Escola
  ConteudoOnlinePerfil --> ConteudoOnline
  ConteudoOnlinePerfil --> PerfilAcesso
  ConteudoOnlineRede --> ConteudoOnline
  ConteudoOnlineRede --> Rede
  ConteudoOnlineTurma --> ConteudoOnline
  ConteudoOnlineTurma --> Turma
  ControleMatricula --> PerfilAcesso
  ControleMatricula --> Rede
  CoordenadorDisciplina --> Disciplina
  CoordenadorDisciplina --> PessoaEscolaAcesso
  CoordenadorDisciplina --> Serie
  CoordenadorEscola --> Escola
  CoordenadorEscola --> Pessoa
  CoordenadorEscola --> Rede
  CoordenadorEscola --> Segmento
  Data --> AnoLetivo
  DataEspecificaDeUmaRecorrencia --> CalendarioEventoRecorrencia
  DiaLetivoExtra --> AnoLetivo
  DiaLetivoExtra --> Escola
  DiarioClasseConfiguracao --> Rede
  DiaSemAula --> Turma
  DiaSemAulaMotivo --> AnoLetivo
  DiaSemAulaMotivo --> DiaSemAulaTipo
  DiaSemAulaMotivo --> Escola
  DiaSemAulaTurma --> Turma
  DiaSemAulaTurma --> DiaSemAulaMotivo
  DiretorEscola --> Escola
  DiretorEscola --> Pessoa
  DiretorEscola --> Rede
  Disciplina --> Disciplina
  Disciplina --> GrupoDisciplina
  Disciplina --> Rede
  DisciplinaDeParaImportacao --> Disciplina
  DisciplinaHisDisciplina --> Disciplina
  DisciplinaHisDisciplina --> HisDisciplina
  DisciplinaPadrao --> TipoRede
  Disciplinas --> EscolaSerieDisciplina
  Disciplinas --> PessoaEscolaAcesso
  DispositivoConectado --> AlunoEscola
  DissidioAnoLetivo --> AnoLetivo
  DissidioAnoLetivo --> Dissidio
  DocumentoPedagogicoRede --> AnoLetivo
  DocumentoPedagogicoRede --> DocumentoPedagogico
  DocumentoPedagogicoRede --> Rede
  DuracaoTempoAula --> RedeSerie
  EnvioLeitura --> Agrupamento
  EnvioLeitura --> Escola
  EnvioLeitura --> LeituraTipoRedacao
  EnvioLeitura --> POATurma
  EnvioLeitura --> Prova
  EnvioLeitura --> Serie
  EnvioLeitura --> LeituraTipo
  EnvioLeitura --> Turno
  EnvioLeitura --> GradeRedacao
  EnvioLeituraCartao --> AlunoCartao
  EnvioLeituraCartao --> EnvioLeitura
  EnvioLeituraCartao --> LeituraCartaoStatus
  EnvioLeituraCartao --> RedacaoDigital
  EnvioLeituraCartao --> EnvioLeituraCartao
  EnvioLeituraCartaoResposta --> EnvioLeituraCartao
  EnvioLeituraStatus --> EnvioLeitura
  EnvioLeituraStatus --> LeituraStatus
  Escola --> Cidade
  Escola --> Escola
  Escola --> Estado
  Escola --> Rede
  Escola --> TipoEscola
  EscolaAnoLetivo --> AnoLetivo
  EscolaAnoLetivo --> Escola
  EscolaConfiguracao --> Escola
  EscolaFeriado --> Escola
  EscolaFeriado --> Rede
  EscolaFeriado --> Turma
  EscolaGerencial --> Rede
  EscolaGerencialEscola --> AnoLetivo
  EscolaGerencialEscola --> Escola
  EscolaGerencialEscola --> EscolaGerencial
  EscolaGSuiteCredential --> Escola
  EscolaGSuiteCredential --> Rede
  EscolaMeta --> AnoLetivo
  EscolaMeta --> Escola
  EscolaMeta --> TipoMeta
  EscolaPagamento --> RedePagamento
  EscolaPagamentoEscola --> AnoLetivo
  EscolaPagamentoEscola --> Escola
  EscolaPagamentoEscola --> EscolaPagamento
  EscolaSerie --> Agrupamento
  EscolaSerie --> AnoLetivo
  EscolaSerie --> Escola
  EscolaSerie --> Serie
  EscolaSerie --> TipoSerie
  EscolaSerieCargaHoraria --> Disciplina
  EscolaSerieCargaHoraria --> EscolaSerie
  EscolaSerieDisciplina --> Disciplina
  EscolaSerieDisciplina --> EscolaSerie
  EscolaSerieDisciplinaCiclo --> EscolaSerieDisciplina
  EscolaSerieDisciplinaCiclo --> RedeSerieCiclo
  EscolaSerieDisciplinaEletiva --> EscolaSerie
  EscolaSerieDisciplinaEletiva --> EscolaSerieDisciplina
  EscolaSerieDisciplinaGrupoDisciplina --> EscolaSerieDisciplina
  EscolaSerieDisciplinaGrupoDisciplina --> GrupoDisciplina
  EscolaSerieEtapa --> EscolaSerie
  EscolaSerieEtapa --> Etapa
  EspecialistaPessoa --> AnamnesePessoaResposta
  EspecialistaPessoa --> Pessoa
  EspecialistaPessoa --> TipoProfissionalSaude
  Estado --> Pais
  EstatisticaClassroom --> AnoLetivo
  EstatisticaClassroom --> Disciplina
  EstatisticaClassroom --> Escola
  EstatisticaClassroom --> Rede
  EstatisticaClassroom --> Segmento
  EstatisticaClassroom --> Serie
  EstatisticaClassroom --> Turma
  EstatisticaTurmaClassroom --> EstatisticaClassroom
  EstatisticaTurmaClassroom --> TurmaClassroom
  EstruturaAvaliacao --> Agrupamento
  EstruturaAvaliacao --> AnoLetivo
  EstruturaAvaliacao --> Ciclo
  EstruturaAvaliacao --> EstruturaAvaliacao
  EstruturaAvaliacao --> ItinerarioFormativoCiclo
  EstruturaAvaliacao --> Rede
  EstruturaAvaliacao --> TipoAvaliacao
  EstruturaAvaliacao --> TipoCartaoResposta
  EstruturaAvaliacao --> TipoResultado
  EstruturaAvaliacao --> TipoSubstituicao
  EstruturaAvaliacaoAprovacao --> Escola
  EstruturaAvaliacaoAprovacao --> EstruturaAvaliacao
  EstruturaAvaliacaoConfiguracao --> TipoArredondamento
  EstruturaAvaliacaoConfiguracao --> Agrupamento
  EstruturaAvaliacaoConfiguracao --> AnoLetivo
  EstruturaAvaliacaoConfiguracao --> GrupoNotaFormativa
  EstruturaAvaliacaoConfiguracao --> Rede
  EstruturaAvaliacaoConfiguracao --> TipoCalculo
  EstruturaAvaliacaoConfiguracao --> EstruturaAvaliacaoConfiguracao
  EstruturaAvaliacaoConfiguracaoEscopo --> EscopoBoletim
  EstruturaAvaliacaoConfiguracaoEscopo --> EstruturaAvaliacaoConfiguracao
  EstruturaAvaliacaoImportacao --> Agrupamento
  EstruturaAvaliacaoImportacao --> AnoLetivo
  EstruturaAvaliacaoImportacao --> EstruturaAvaliacaoEscopo
  EstruturaAvaliacaoImportacao --> Rede
  EstruturaAvaliacaoImportacaoAprovacao --> EstruturaAvaliacaoImportacao
  EstruturaAvaliacaoImportacaoAprovacao --> EstruturaAvaliacao
  EstruturaAvaliacaoImportacaoEstrutura --> Ciclo
  EstruturaAvaliacaoImportacaoEstrutura --> EstruturaAvaliacaoImportacao
  EstruturaAvaliacaoImportacaoEstrutura --> EstruturaAvaliacao
  EstruturaAvaliacaoImportacaoEstrutura --> Etapa
  EstruturaAvaliacaoImportacaoEstrutura --> TipoAvaliacao
  EstruturaAvaliacaoImportacaoSerie --> EstruturaAvaliacaoImportacao
  EstruturaAvaliacaoImportacaoSerie --> Serie
  EstruturaAvaliacaoLiberacaoBoletim --> Agrupamento
  EstruturaAvaliacaoLiberacaoBoletim --> AnoLetivo
  EstruturaAvaliacaoLiberacaoBoletim --> Rede
  EstruturaAvaliacaoLiberacaoSituacao --> Agrupamento
  EstruturaAvaliacaoLiberacaoSituacao --> AnoLetivo
  EstruturaAvaliacaoLiberacaoSituacao --> Rede
  EstruturaAvaliacaoOrdemDisciplina --> Agrupamento
  EstruturaAvaliacaoOrdemDisciplina --> AnoLetivo
  EstruturaAvaliacaoOrdemDisciplina --> Disciplina
  EstruturaAvaliacaoOrdemDisciplina --> Rede
  EstruturaAvaliacaoSubstituicao --> EstruturaAvaliacao
  Etapa --> AnoLetivo
  Etapa --> EstruturaAvaliacaoEscopo
  Etapa --> Etapa
  Etapa --> Rede
  ExcecoesDeAcesso --> Escola
  ExcecoesDeAcesso --> Funcionalidade
  ExcecoesDeAcesso --> PerfilAcesso
  ExcecoesDeAcesso --> Rede
  ExtracaoBaseDeNotas --> AnoLetivo
  FaleConosco --> Escola
  FaleConosco --> Rede
  FichaMedica --> Pessoa
  Filiacao --> Pessoa
  FolhaAlteracaoCarga --> Periodo
  FolhaChecklistCargasIndevidas --> Periodo
  FolhaChecklistCargasIndevidas --> ProfessorPerfilVigente
  FolhaChecklistCargasIndevidas --> Situacao
  FolhaChecklistProfessorAcimaDoLimite --> Periodo
  FolhaChecklistProfessorAcimaDoLimite --> ProfessorPerfilVigente
  FolhaChecklistProfessorSemSC --> Periodo
  FolhaChecklistProfessorSemSC --> ProfessorPerfilVigente
  FolhaChecklistSemTitular --> Disciplina
  FolhaChecklistSemTitular --> Periodo
  FolhaChecklistSemTitular --> Turma
  FolhaProfessorLicenca --> Disciplina
  FolhaProfessorLicenca --> Escola
  FolhaProfessorLicenca --> MotivosSaida
  FolhaProfessorLicenca --> Periodo
  FolhaProfessorLicenca --> ProfessorPerfilVigente
  FolhaProfessorLicenca --> Segmento
  FolhaProfessorPorPeriodo --> Periodo
  FolhaProfessorPorPeriodo --> ProfessorPerfilVigente
  FolhaProfessorPorPeriodoTotal --> Periodo
  FolhaProfessorPorPeriodoTotal --> ProfessorPerfilVigente
  FormularioAtendimento --> MotivoAtendimento
  FormularioAtendimento --> TipoPublicoAtendido
  FormularioAtendimentoQuestao --> FormularioAtendimento
  FormularioAtendimentoQuestao --> FormularioAtendimentoQuestaoOpcao
  FormularioAtendimentoQuestaoOpcao --> FormularioAtendimentoQuestao
  FormularioAtendimentoResposta --> Atendimento
  FormularioAtendimentoResposta --> FormularioAtendimentoQuestao
  FormularioAtendimentoResposta --> Ocorrencia
  FormularioAtendimentoRespostaOpcao --> FormularioAtendimentoResposta
  FormularioAtendimentoRespostaOpcao --> Disciplina
  FormularioAtendimentoRespostaOpcao --> FormularioAtendimentoQuestaoOpcao
  FotoPessoa --> AnoLetivo
  FotoPessoa --> Pessoa
  FrequenciaProfessor --> FrequenciaProfessor
  FrequenciaProfessor --> MotivoFrequenciaProfessorTipoPresenca
  FrequenciaProfessor --> PessoaEscolaAcesso
  FrequenciaProfessorSubstituto --> FrequenciaProfessor
  FrequenciaProfessorSubstituto --> PessoaEscolaAcesso
  FrequenciaProfessorSubstituto --> Turma
  Funcionalidade --> AnoLetivo
  FuncionalidadeAcessada --> PerfilAcesso
  FuncionalidadeAcessada --> Escola
  FuncionalidadeAcessada --> MenuItem
  FuncionalidadeAcessada --> Rede
  FuncionalidadeSegmento --> Funcionalidade
  FuncionalidadeSegmento --> Segmento
  FuncionalidadeTipoPresenca --> Funcionalidade
  FuncionalidadeTipoPresenca --> TipoPresenca
  GabaritoComentado --> Simulado
  GradeHoraria --> AnoLetivo
  GradeHoraria --> Rede
  GradeHorariaLinha --> GradeHoraria
  GradeRedacaoAgrupamento --> Agrupamento
  GradeRedacaoAgrupamento --> GradeRedacao
  GradeRedacaoAgrupamentoProva --> GradeRedacaoAgrupamento
  GradeRedacaoAgrupamentoProva --> Prova
  GradeRedacaoAgrupamentoRede --> Rede
  GradeRedacaoAgrupamentoRede --> GradeRedacaoAgrupamento
  GradeRedacaoCompetencia --> Competencia
  GradeRedacaoCompetencia --> GradeRedacao
  GradeRedacaoCompetenciaLegenda --> Competencia
  GradeRedacaoCompetenciaLegenda --> GradeRedacao
  GradeRedacaoCompetenciaLegenda --> LegendaRedacao
  GradeRedacaoCompetenciaLegendaIA --> Competencia
  GradeRedacaoCompetenciaLegendaIA --> GradeRedacao
  GradeRedacaoCompetenciaLegendaIA --> LegendaRedacao
  GradeRedacaoLegenda --> GradeRedacao
  GradeRedacaoLegenda --> LegendaRedacao
  GradeRedacaoRegraGeral --> GradeRedacao
  GradeRedacaoRegraGeral --> RegraGeralRedacao
  GrupoNotaFormativa --> Rede
  GrupoPerguntaPerfilAcesso --> GrupoPergunta
  GrupoPerguntaPerfilAcesso --> PerfilAcesso
  GuiaFinanceiro --> Rede
  GuiaPortal --> PerfilAcesso
  GuiaPortal --> Rede
  HabilidadeEnem --> AreaConhecimento
  HabilidadesBNCC --> Disciplina
  HabilidadesENEM --> AreaConhecimento
  HisAnoLetivo --> AnoLetivo
  HisCargaHoraria --> HisAnoLetivo
  HisCargaHoraria --> HisDisciplina
  HisCargaHoraria --> HisSerie
  HisCargaHoraria --> Rede
  HisEscola --> Escola
  HisEscolaComp --> HisAnoLetivo
  HisEscolaComp --> HisEscola
  HisEscolaComp --> HisSerie
  HisEscolaCompDisc --> HisDisciplina
  HisEscolaCompDisc --> HisEscolaComp
  HisHistorico --> HisFundamentacaoLegal
  HisHistorico --> PessoaEscolaAcesso
  HisHistoricoAnoLetivo --> HisEscolaComp
  HisHistoricoAnoLetivo --> HisHistorico
  HisHistoricoAnoLetivo --> HisResultadoFinal
  HisHistoricoNotas --> HisEscolaCompDisc
  HisHistoricoNotas --> HisHistoricoAnoLetivo
  HisNucleoComum --> HisDisciplina
  HisNucleoComum --> HisSerie
  HistoricoHoraAulaPgto --> HoraAulaPgto
  HistoricoHoraAulaSegmentoPgto --> HoraAulaSegmentoPgto
  HoraAulaPadrao --> AnoLetivo
  HoraAulaPadrao --> ClassePagamento
  HoraAulaPadrao --> EscolaPagamento
  HoraAulaPadrao --> SegmentoPagamento
  HoraAulaPgto --> TipoHoraAula
  HoraAulaPgto --> DissidioAnoLetivo
  HoraAulaPgto --> UnidadePgto
  HoraAulaSegmentoPgto --> ClasseTurmaSegmentoPgto
  HoraAulaSegmentoPgto --> DissidioAnoLetivo
  HoraAulaSegmentoPgto --> TipoHoraAula
  HoraAulaSegmentoPgto --> UnidadePgto
  IconDisciplinaPladGame --> Disciplina
  ImportacaoTRI --> ProvaModelo
  ImportacaoTRILinha --> ImportacaoTRI
  Inbox --> Escola
  Inbox --> CanalEnvio
  Inbox --> Comunicado
  IndicadorEscola --> AnoLetivo
  IndicadorEscola --> Escola
  IndicadorEscola --> Indicador
  IndicadorEscolaObjeto --> IndicadorEscola
  IndicadorEscolaObjeto --> ManutencaoOpcoes
  IndicadorEscolaObjetoValor --> IndicadorEscolaObjeto
  IndicadorEscolaValor --> IndicadorEscola
  IndicadorEscolaValorOrcado --> IndicadorEscola
  InformacaoSaidaAluno --> AlunoEscola
  InformacaoSaidaAluno --> InformacaoSaida
  InformacaoSaidaAutorizacao --> InformacaoSaida
  InformacaoSaidaAutorizacaoDiaSemana --> InformacaoSaidaAutorizacao
  InformacaoSaidaAutorizacaoOutros --> InformacaoSaidaAutorizacao
  InformacaoSaidaAutorizacaoOutrosDetalhe --> InformacaoSaidaAutorizacaoOutros
  InformacaoSaidaAutorizacaoResponsavel --> InformacaoSaidaAutorizacao
  InformacaoSaidaAutorizacaoResponsavel --> Pessoa
  InformacaoSaidaAutorizacaoResponsavelDetalhe --> InformacaoSaidaAutorizacaoResponsavel
  InformacaoSaidaAutorizacaoServico --> InformacaoSaidaAutorizacao
  InformacaoSaidaLogModificacao --> AlunoEscola
  ItinerarioFormativo --> ItinerarioFormativoCiclo
  ItinerarioFormativo --> ItinerarioFormativoTipo
  ItinerarioFormativoOferta --> ItinerarioFormativo
  ItinerarioFormativoOferta --> ItinerarioFormativoPeriodo
  ItinerarioFormativoPeriodo --> ItinerarioFormativoCiclo
  ItinerarioFormativoRedeSerie --> ItinerarioFormativo
  ItinerarioFormativoRedeSerie --> RedeSerie
  ItinerarioFormativoRedeSerieDisciplina --> Disciplina
  ItinerarioFormativoRedeSerieDisciplina --> ItinerarioFormativoRedeSerie
  JobParameter --> Job
  LancamentoComportamento --> Disciplina
  LancamentoComportamento --> Pessoa
  LancamentoComportamento --> TipoComportamento
  LancamentoComportamento --> Turma
  LancamentoNotasBusca --> Agrupamento
  LancamentoNotasBusca --> AnoLetivo
  LancamentoNotasBusca --> Chamada
  LancamentoNotasBusca --> Disciplina
  LancamentoNotasBusca --> Escola
  LancamentoNotasBusca --> Rede
  LancamentoNotasBusca --> TipoAvaliacao
  LancamentoNotasBusca --> Turma
  LancamentoNotasStatusPorTurma --> Avaliacao
  LancamentoNotasStatusPorTurma --> Chamada
  LancamentoNotasStatusPorTurma --> ProvaTurma
  LegendaRedacao --> TipoLegenda
  LeituraImportacao --> LeituraTipoImportacao
  LeituraImportacaoLinha --> LeituraImportacao
  LeituraTipoRede --> AnoLetivo
  LeituraTipoRede --> LeituraTipo
  LeituraTipoRede --> Rede
  LiberacaoBoletim --> EstruturaAvaliacao
  LiberacaoBoletim --> Turma
  LiberacaoRede --> Rede
  LiberacaoRede --> Simulado
  LiberacaoUnidade --> Escola
  LiberacaoUnidade --> Simulado
  LIV_AcaoMarketing --> LIV_TipoMaterial
  LIV_AcaoMarketing --> LIV_ClasseSubtipoMaterial
  LIV_AcaoMarketing --> LIV_SubTipoMaterial
  LIV_AcaoMarketingSegmento --> LIV_AcaoMarketing
  LIV_AcaoMarketingSegmento --> SegmentoLIV
  LIV_AtualizacaoCadastro --> LIV_ImportacaoDados
  LIV_AtualizacaoCadastroAnos --> LIV_AtualizacaoCadastroIndividual
  LIV_AtualizacaoCadastroAnos --> Serie
  LIV_AtualizacaoCadastroCargos --> LIV_AtualizacaoCadastroIndividual
  LIV_Carometro --> Usuario
  LIV_Carometro --> AnoLetivo
  LIV_Carometro --> Escola
  LIV_Carometro --> Serie
  LIV_Carometro --> Turma
  LIV_CarometroComentario --> PessoaEscolaAcesso
  LIV_CarometroComentario --> Escola
  LIV_CarometroComentario --> Pessoa
  LIV_CarometroComentario --> Segmento
  LIV_CarometroComentario --> Serie
  LIV_CarometroComentario --> Turma
  LIV_ClasseSubtipoMaterial --> LIV_SubTipoMaterial
  LIV_Comportamento --> Serie
  LIV_EscolaSegmentoLivMais --> Escola
  LIV_EscolaSegmentoLivMais --> SegmentoLIV
  LIV_FeedbackAula --> AnoLetivo
  LIV_FeedbackAula --> LIV_FeedbackCadastroAulas
  LIV_FeedbackAula --> Escola
  LIV_FeedbackAula --> Pessoa
  LIV_FeedbackAula --> Serie
  LIV_FeedbackAulaRespostas --> LIV_FeedbackAula
  LIV_FeedbackAulaRespostas --> LIV_FeedbackPerguntas
  LIV_HabilidadesAct --> SegmentoLIV
  LIV_ImportacaoDados --> Escola
  LIV_ImportacaoDadosLinhasUsuario --> LIV_ImportacaoDados
  LIV_ImportacaoDadosLinhasUsuario --> PerfilAcesso
  LIV_ImportacaoDadosLog --> LIV_ImportacaoDados
  LIV_INEPEscola --> Escola
  LIV_LOG_Acessos --> Escola
  LIV_LOG_Engajamento --> Escola
  LIV_LOG_MaterialLinks --> LIV_MaterialLinks
  LIV_LOG_MaterialSerieVideoLinks --> LIV_MaterialSerieVideoLinks
  LIV_LOG_TermosDeUso --> Escola
  LIV_LOG_TipoMaterial --> Escola
  LIV_LOG_TipoMaterial --> Serie
  LIV_LOG_TipoMaterial --> LIV_Material
  LIV_Material --> LIV_TipoMaterial
  LIV_Material --> AnoLetivo
  LIV_MaterialLinks --> LIV_Material
  LIV_MaterialLinks --> Pessoa
  LIV_MaterialSegmento --> LIV_Material
  LIV_MaterialSegmento --> SegmentoLIV
  LIV_MaterialSerie --> LIV_Material
  LIV_MaterialSerie --> TipoSerie
  LIV_MaterialSerieVideo --> LIV_Material
  LIV_MaterialSerieVideoLinks --> Pessoa
  LIV_MaterialSerieVideoLinks --> LIV_MaterialSerieVideo
  LIV_Notificacao --> PerfilAcesso
  LIV_NotificacaoUsuario --> LIV_Notificacao
  LIV_ParametroEscolaMaterial --> LIV_ParametroEscola
  LIV_ParametroEscolaMaterial --> LIV_TipoMaterial
  LIV_PercursoTrilhaMomento --> LIV_PercursoMomento
  LIV_PercursoTrilhaMomentoLink --> LIV_PercursoTrilhaMomento
  LIV_PercursoTrilhaMomentoLink --> LIV_MaterialPlanoAula
  LIV_PercursoTrilhaMomentoLinkItem --> LIV_PercursoTrilhaMomentoLink
  LIV_PercursoTrilhaMomentoLinkItem --> LIV_MaterialPlanoAula
  LIV_PercursoTrilhaMomentoProgresso --> LIV_PercursoTrilhaMomento
  LIV_PerfilAcessoAcaoMarketing --> LIV_AcaoMarketing
  LIV_PerfilAcessoAcaoMarketing --> PerfilAcesso
  LIV_PerfilAcessoMaterial --> LIV_Material
  LIV_PerfilAcessoMaterial --> PerfilAcesso
  LIV_PerfilAcessoNoticia --> LIV_Noticia
  LIV_PerfilAcessoNoticia --> PerfilAcesso
  LIV_PesquisaAnos --> LIV_Pesquisa
  LIV_PesquisaAnos --> Serie
  LIV_PesquisaQuestoes --> LIV_Pesquisa
  LIV_PessoaSerie --> Escola
  LIV_PessoaSerie --> Pessoa
  LIV_PessoaSerie --> Serie
  LIV_Playbook --> SegmentoLIV
  LIV_Questionario --> Escola
  LIV_Questionario --> Pessoa
  LIV_Questionario --> Turma
  LIV_QuestionarioItem --> LIV_Questionario
  LIV_StatusPlanoAula --> AnoLetivo
  LIV_StatusPlanoAula --> SegmentoLIV
  LIV_SubTipoMaterial --> LIV_TipoMaterial
  LIV_UsuarioInativo --> Escola
  LIV_UsuarioSegmento --> SegmentoLIV
  LIV_Webinar --> Escola
  LIV_Webinar --> Serie
  LIV_WebinarPerfilAcesso --> LIV_Webinar
  LIV_WebinarSegmento --> LIV_Webinar
  LogAcessoPlataformaAdaptativa --> Assunto
  LogAcessoPlataformaAdaptativa --> Disciplina
  LogAcessoPlataformaAdaptativa --> LogAcessoProduto
  LogAcessoProduto --> Atualidade
  LogAcessoProduto --> Disciplina
  LogAcessoProduto --> LogAcesso
  LogAcessoProduto --> Produto
  LogAcessoProduto --> PublicacaoCanal
  LogAcessoProduto --> Serie
  LogAcessoProduto --> AlunoEscola
  LogAcessoProduto --> ConteudoOnline
  LogAcessoResultadoBimestral --> AlunoEscola
  LogAcessoResultadoBimestral --> Ciclo
  LogAgenteImportacaoColecaoComercial --> Escola
  LogAlteracaoPrazoCorrecaoRedacao --> Usuario
  LogAlteracaoPrazoCorrecaoRedacao --> Redacao
  LogClassroom --> TipoLogClassroom
  LogClassroom --> Disciplina
  LogClassroom --> OperacaoClassroom
  LogClassroom --> Pessoa
  LogClassroom --> Turma
  LogEnturmacao --> AlunoEscola
  LogEnturmacao --> Turma
  LogErroClassroom --> Disciplina
  LogErroClassroom --> OperacaoClassroom
  LogErroClassroom --> Pessoa
  LogErroClassroom --> Turma
  LogMaterialEletiva --> MaterialEletivaConteudo
  LogMaterialEletiva --> SemestreEletiva
  LogQuestaoSimilar --> Questao
  LogTermosDeUsoPortal --> TermosDeUso
  LogUpdateDadosPessoais --> AnoLetivo
  LogUpdateDadosPessoais --> Pessoa
  LogUpdateDadosPessoais --> Rede
  LogUpdateFotoPessoa --> AnoLetivo
  LogUpdateFotoPessoa --> Pessoa
  LogUpdateFotoPessoa --> Rede
  MacroTurmaConfiguracao --> AnoLetivo
  MacroTurmaConfiguracao --> MacroTurma
  MacroTurmaConfiguracao --> RedePagamento
  MacroTurmaConfiguracao --> SegmentoPagamento
  MacroTurmaConfiguracao --> SegmentoSindical
  MacroTurmaConfiguracao --> TipoEvento
  MacroTurmaIntelpedTurma --> MacroTurmaIntelped
  MacroTurmaIntelpedTurma --> Turma
  Marca --> TipoRede
  MaterialComplementar --> ConteudoOnline
  MaterialComplementar --> MaterialEletivaConteudo
  MaterialComplementar --> SemestreEletiva
  MaterialComplementar --> AnoLetivo
  MaterialComplementar --> MaterialComplementar
  MaterialComplementar --> Rede
  MaterialComplementarEscolaSerie --> EscolaSerie
  MaterialDidatico --> AnoLetivo
  MaterialDidatico --> Serie
  MaterialDidatico --> MaterialDidatico
  MaterialDidaticoColecaoComercial --> ColecaoComercial
  MaterialDidaticoColecaoComercial --> MaterialDidaticoPlanejamento
  MaterialDidaticoContratoData --> MaterialDidaticoEscola
  MaterialDidaticoContratoData_backup --> MaterialDidaticoEscola_backup
  MaterialDidaticoData --> MaterialDidatico
  MaterialDidaticoDeParaTipoMaterialImportacao --> MaterialDidaticoTipoMaterial
  MaterialDidaticoDeParaVolume --> MaterialDidatico
  MaterialDidaticoEscola --> AnoLetivo
  MaterialDidaticoEscola --> Escola
  MaterialDidaticoEscola --> MaterialDidaticoCapa
  MaterialDidaticoEscola --> MaterialDidaticoTipoFrete
  MaterialDidaticoEscola_backup --> AnoLetivo
  MaterialDidaticoEscola_backup --> Escola
  MaterialDidaticoEscola_backup --> Serie
  MaterialDidaticoEscolaContrato --> MaterialDidatico
  MaterialDidaticoEscolaContrato --> MaterialDidaticoEscola
  MaterialDidaticoEscolaContrato_backup --> Escola
  MaterialDidaticoEscolaContrato_backup --> Fornecedor
  MaterialDidaticoEscolaContrato_backup --> MaterialDidaticoTipoFrete
  MaterialDidaticoEscolaContratoComp --> MaterialDidaticoEscolaContrato
  MaterialDidaticoEscolaContratoComp --> MaterialDidaticoProduto
  MaterialDidaticoEscolaPedido --> MaterialDidaticoEscolaContrato
  MaterialDidaticoEscolaPedido --> MaterialDidaticoTipoPedido
  MaterialDidaticoEscolaPedido --> MaterialDidaticoStatusPedido
  MaterialDidaticoEscolaPedido --> MaterialDidaticoLote
  MaterialDidaticoEscolaPedido_backup --> MaterialDidaticoEscola_backup
  MaterialDidaticoEscolaPedidoExtra --> MaterialDidaticoEscola
  MaterialDidaticoEscolaPedidoExtra_backup --> MaterialDidaticoEscola_backup
  MaterialDidaticoEscolaPedidoHistorico --> MaterialDidaticoEscolaPedido_backup
  MaterialDidaticoEscolaPedidoHistorico --> MaterialDidaticoStatus
  MaterialDidaticoEscolaPedidoHistorico_backup --> MaterialDidaticoEscolaPedido_backup
  MaterialDidaticoEscolaPedidoHistorico_backup --> MaterialDidaticoStatus
  MaterialDidaticoEscolaPlanejamento --> AnoLetivo
  MaterialDidaticoEscolaPlanejamento --> Escola
  MaterialDidaticoLote --> MaterialDidaticoTipoFrete
  MaterialDidaticoLote --> MaterialDidaticoTipoMovimento
  MaterialDidaticoLote --> MaterialDidaticoCondicaoPagamento
  MaterialDidaticoMonitoriaPedido --> MaterialDidaticoMonitoriaAvaliacao
  MaterialDidaticoMonitoriaPedido --> MaterialDidaticoMonitoriaQuestao
  MaterialDidaticoMonitoriaPedido --> MaterialDidaticoMonitoriaStatus
  MaterialDidaticoMonitoriaQuestao --> MaterialDidaticoTipoQuestao
  MaterialDidaticoMonitoriaQuestao --> MaterialDidaticoVolumeModulo
  MaterialDidaticoPlanejamento --> MaterialDidaticoTipoMaterial
  MaterialDidaticoPlanejamento --> MaterialDidaticoVolume
  MaterialDidaticoPlanejamento --> Rede
  MaterialDidaticoPlanejamentoConteudo --> MaterialDidaticoPlanejamento
  MaterialDidaticoProblema --> MaterialDidaticoProblemaAssunto
  MaterialDidaticoProblema --> MaterialDidaticoProblemaTipo
  MaterialDidaticoProblema --> MaterialDidaticoVolume
  MaterialDidaticoProduto --> MaterialDidatico
  MaterialDidaticoProduto --> MaterialDidaticoCapa
  MaterialDidaticoVolume --> AnoLetivo
  MaterialDidaticoVolume --> Disciplina
  MaterialDidaticoVolume --> MaterialDidatico
  MaterialDidaticoVolume --> Serie
  MaterialDidaticoVolumeModulo --> MaterialDidaticoVolume
  MaterialEletiva --> SemestreEletiva
  MaterialEletiva --> AnoLetivo
  MaterialEletiva --> Disciplina
  MaterialEletivaConteudo --> ConteudoOnlineTipo
  MaterialEletivaConteudo --> MaterialEletiva
  MediaAvaliacaoEscola --> Prova
  MediaAvaliacaoEscola --> Escola
  MediaAvaliacaoEscola --> Avaliacao
  MedicamentoFormato --> Formato
  MedicamentoFormato --> Medicamento
  MedicamentoPrescrito --> Pessoa
  MedicamentoPrescrito --> PessoaDocumento
  MedicamentoPrescritoHorario --> MedicamentoPrescrito
  MeetTurmaClassroomPessoa --> Pessoa
  MenuItem --> Funcionalidade
  MenuItem --> MenuItem
  MenuItem --> PerfilAcesso
  MenuItem --> TipoRede
  MenuItemLateral --> Funcionalidade
  MenuItemLateral --> MenuItemLateral
  MenuLink --> Escola
  MetaAtendimento --> AnoLetivo
  MetaAtendimentoAluno --> MetaAtendimento
  MetaAtendimentoAluno --> Pessoa
  MetaAtendimentoTipoAtendimento --> MetaAtendimento
  MetaAtendimentoTipoAtendimento --> Segmento
  MetaAtendimentoTipoAtendimento --> TipoAtendimento
  MetaEvasao --> Escola
  MetaEvasao --> Rede
  ModuloFeedback --> Simulado
  ModuloFeedback --> Pessoa
  MonitoriaEscala --> Disciplina
  MonitoriaEscala --> Escola
  MonitoriaEscala --> MonitoriaMonitor
  MonitoriaEscalaAlunosPresentes --> AlunoEscola
  MonitoriaEscalaAlunosPresentes --> MonitoriaEscala
  MonitoriaMonitor --> Cidade
  MonitoriaMonitor --> Pessoa
  MonitoriaMonitor --> Rede
  MonitoriaMonitorDisciplina --> Disciplina
  MonitoriaMonitorDisciplina --> MonitoriaMonitor
  MonitoriaMonitorPresenca --> MonitoriaEscala
  MonitoriaMonitorPresenca --> MonitoriaMonitor
  MonitoriaMonitorPresenca --> TipoAbonoFalta
  MonitoriaMonitorPresenca --> TipoPresenca
  MonitorTurmaDisciplina --> Disciplina
  MonitorTurmaDisciplina --> PessoaEscolaAcesso
  MonitorTurmaDisciplina --> Turma
  MotivoAtendimento --> TipoAtendimento
  MotivoAtendimentoTipoPublicoAtendido --> MotivoAtendimento
  MotivoAtendimentoTipoPublicoAtendido --> TipoPublicoAtendido
  MotivoFrequenciaProfessor --> MotivoFrequenciaProfessor
  MotivoFrequenciaProfessorTipoPresenca --> MotivoFrequenciaProfessor
  MotivoFrequenciaProfessorTipoPresenca --> Rede
  MotivoFrequenciaProfessorTipoPresenca --> TipoPresenca
  MotivosSaida --> Rede
  NaoRecalcularBaseDeSeriesPorAluno --> Pessoa
  NomeUraniaDisciplina --> Rede
  NomeUraniaDisciplinaLinha --> NomeUraniaDisciplina
  NomeUraniaTurma --> AnoLetivo
  NomeUraniaTurmaLinha --> NomeUraniaTurma
  NotaFormativa --> TipoNotaFormativa
  NotaTransferencia --> Disciplina
  NotaTransferencia --> Pessoa
  Ocorrencia --> EscolaSerie
  Ocorrencia --> RedeSerie
  Ocorrencia --> TipoOcorrencia
  OcorrenciaEscolaEleva --> Pessoa
  OcorrenciaEscolaEleva --> TipoOcorrenciaEscolaEleva
  OpcaoResposta --> Pergunta
  Opiniao --> AlunoEscola
  Opiniao --> MaterialDidaticoMonitoriaQuestao
  Opiniao --> PerfilAcesso
  Opiniao --> Produto
  Opiniao --> PublicacaoCanal
  Opiniao --> Questao
  OrdenacaoAtendimentoRede --> AnoLetivo
  OrdenacaoAtendimentoRede --> OrdenacaoAtendimento
  OrdenacaoAtendimentoRede --> Rede
  PainelAlunoTrocaAlunoEscola --> AlunoEscola
  ParametrosFolhaPorRede --> Rede
  ParametrosFolhaPorRede --> ParametrosFolha
  PercentualFrequencia --> AnoLetivo
  PercentualFrequencia --> Pessoa
  PercentualFrequencia --> Serie
  PerfilAcessoFuncionalidade --> Escola
  PerfilAcessoFuncionalidade --> Funcionalidade
  PerfilAcessoFuncionalidade --> PerfilAcesso
  PerfilAcessoFuncionalidade --> Rede
  PerfilAcessoFuncionalidadeSegmentoAgrupamento --> Agrupamento
  PerfilAcessoFuncionalidadeSegmentoAgrupamento --> Funcionalidade
  PerfilAcessoFuncionalidadeSegmentoAgrupamento --> Segmento
  PerfilAcessoFuncionalidadeSegmentoAgrupamento --> TipoRede
  PerfilAcessoFuncionalidadeSerie --> Escola
  PerfilAcessoFuncionalidadeSerie --> Funcionalidade
  PerfilAcessoFuncionalidadeSerie --> PerfilAcesso
  PerfilAcessoFuncionalidadeSerie --> Rede
  PerfilAcessoFuncionalidadeSerie --> Serie
  PerfilAcessoTipoRede --> PerfilAcesso
  PerfilAcessoTipoRede --> TipoRede
  PerfilDeAcessoDoUsuario --> PerfilAcesso
  PerfilDeAcessoDoUsuario --> Rede
  PerfilDeAcessoDoUsuario --> TipoRede
  Pergunta --> GrupoPergunta
  Pergunta --> TipoRespostaAnamnese
  PerguntaCondicionalOpcaoResposta --> OpcaoResposta
  PerguntaCondicionalOpcaoResposta --> PerguntaVersaoAnamnese
  PerguntaTipoPergunta --> Pergunta
  PerguntaTipoPergunta --> TipoPergunta
  PerguntaVersaoAnamnese --> Pergunta
  PerguntaVersaoAnamnese --> PerguntaVersaoAnamnese
  PerguntaVersaoAnamnese --> VersaoAnamnese
  PerguntaVersaoAnamneseTipoPergunta --> PerguntaVersaoAnamnese
  PerguntaVersaoAnamneseTipoPergunta --> TipoPergunta
  PerguntaVersaoAnamneseTipoPerguntaOpcaoResposta --> OpcaoResposta
  PerguntaVersaoAnamneseTipoPerguntaOpcaoResposta --> PerguntaVersaoAnamneseTipoPergunta
  PeriodoEscolar --> AnoLetivo
  PeriodoEscolar --> Escola
  PeriodoEscolar --> TipoPeriodoEscolar
  PeriodoLancamentoFrequenciaProfessor --> Rede
  PeriodosDeExclusaoCorretores --> AlocacaoCorretorStatus
  PermissaoDW --> Rede
  PesquisaIntencao --> AnoLetivo
  PesquisaIntencaoPergunta --> PesquisaIntencao
  PesquisaIntencaoPublico --> PesquisaIntencao
  PesquisaIntencaoPublico --> RedeSerie
  PesquisaIntencaoResposta --> PesquisaIntencaoPergunta
  PesquisaNotaAvaliacao --> NotaAvaliacao
  PesquisaNotaAvaliacao --> Pesquisa
  PesquisaOpiniaoPergunta --> PesquisaOpiniaoPergunta
  PesquisaOpiniaoPergunta --> PesquisaOpiniao
  PesquisaOpiniaoPergunta --> PesquisaOpiniaoTipoResposta
  PesquisaOpiniaoResposta --> PesquisaOpiniaoPergunta
  PesquisaOpiniaoUsuario --> PesquisaOpiniao
  PesquisaPublica --> PerfilAcesso
  PesquisaPublica --> Pesquisa
  PesquisaPublica --> RedeSerie
  PesquisaPublico --> Escola
  PesquisaPublico --> Pesquisa
  PesquisaPublico --> Serie
  PesquisaPublicoPerfilAcesso --> PesquisaPublico
  PesquisaPublicoSegmento --> PesquisaPublico
  PesquisaRespondida --> Escola
  PesquisaRespondida --> Serie
  PesquisaResposta --> NotaAvaliacao
  PesquisaResposta --> PerfilAcesso
  PesquisaResposta --> PerfilDeAcessoDoUsuario
  PesquisaResposta --> Pesquisa
  PesquisaResposta --> Pessoa
  PesquisaResposta --> PessoaEscolaAcesso
  PesquisaResultado --> Escola
  PesquisaResultado --> Serie
  PesquisaResultadoPerfilAcesso --> PesquisaResultado
  PesquisaResultadoSegmento --> PesquisaResultado
  PesquisaSatisfacaoPergunta --> PesquisaSatisfacao
  PesquisaSatisfacaoPergunta --> PesquisaSatisfacaoTipoPergunta
  PesquisaSatisfacaoResposta --> PesquisaSatisfacaoPergunta
  PesquisaSatisfacaoResposta --> PesquisaSatisfacaoUsuario
  PesquisaSatisfacaoUsuario --> Escola
  PesquisaSatisfacaoUsuario --> PerfilAcesso
  PesquisaSatisfacaoUsuario --> PesquisaSatisfacao
  PesquisaSatisfacaoUsuario --> Pessoa
  PesquisaSatisfacaoUsuario --> Serie
  PesquisaSatisfacaoUsuario --> Turma
  Pessoa --> Estado
  Pessoa --> Pessoa
  PessoaAprovadaConselho --> Pessoa
  PessoaDadosAlterados --> Pessoa
  PessoaDePara --> AnoLetivo
  PessoaDePara --> Pessoa
  PessoaDocumento --> Pessoa
  PessoaDocumento --> TipoDocumento
  PessoaEscola --> Usuario
  PessoaEscola --> Escola
  PessoaEscola --> Pessoa
  PessoaEscolaAcesso --> PerfilAcesso
  PessoaEscolaAcesso --> PessoaEscola
  PessoaEscolaAcesso --> PessoaEscolaAcesso
  PessoaEscolaAcessoSegmento --> PessoaEscolaAcesso
  PessoaEscolaAcessoSegmento --> Segmento
  PessoaEscolaSerieDisciplina --> EscolaSerieDisciplina
  PessoaEscolaSerieDisciplina --> Pessoa
  PessoaJuridicaAlunoEscola --> AlunoEscola
  PessoaJuridicaAlunoEscola --> PessoaJuridica
  PessoaJuridicaAlunoEscola --> Pessoa
  PessoaRedeEmail --> Pessoa
  PessoaRedeEmail --> Rede
  PessoaSegmento --> AnoLetivo
  PessoaSegmento --> Escola
  PessoaSegmento --> Pessoa
  PessoaSegmento --> Segmento
  PessoaTelefone --> Pessoa
  PessoaTurma --> Pessoa
  PessoaTurma --> Turma
  PLADAvaliacao --> AlunoEscola
  PLADAvaliacao --> Disciplina
  PLADAvaliacao --> PLADMaterialEstudo
  PLADAvaliacao --> RedeSerieDisciplinaAssunto
  PLADAvaliacao --> RedeSerieCicloAssunto
  PLADAvaliacaoQuestao --> PLADAvaliacao
  PLADAvaliacaoQuestao --> Questao
  PLADMaterialEstudo --> Conteudo
  PLADMaterialEstudo --> RedeSerieDisciplinaAssunto
  PLADMaterialEstudo --> RedeSerieCicloAssunto
  PLADNivelAluno --> Disciplina
  PLADNivelAluno --> RedeSerieDisciplinaAssunto
  PLADNivelAluno --> RedeSerieCicloAssunto
  PLADQuestaoGame --> Questao
  PLADQuestaoGame --> RedeSerieCicloAssunto
  PLADQuestaoGame --> RedeSerieDisciplinaAssunto
  POAAgenda --> POATurma
  POAAluno --> POAPessoa
  POAAluno --> POATurma
  POAAlunoOpcao --> POAAluno
  POAAlunoOpcao --> POAAvaliacao
  POAAlunoOpcao --> POAOpcao
  POAAvaliacao --> POAProfessor
  POAAvaliacao --> POAQuesito
  POAAvaliacaoResultado --> POAAvaliacao
  POACartao --> EnvioLeituraCartao
  POACartao --> POATurma
  POACartaoOpcao --> POACartao
  POACartaoOpcao --> POAOpcao
  POAOpcao --> POAPeriodo
  POAPeriodo --> AnoLetivo
  POAPeriodo --> POATipoAplicacao
  POAPeriodoRede --> POAPeriodo
  POAPeriodoRede --> Rede
  POAPessoa --> Pessoa
  POAProfessor --> Disciplina
  POAProfessor --> POAPessoa
  POAProfessor --> POATurma
  POAQuesito --> POAPeriodo
  POAQuesito --> Segmento
  POATurma --> Turma
  POATurmaStatus --> POAStatus
  POATurmaStatus --> POATurma
  Pontuacao --> Agrupamento
  Pontuacao --> Competencia
  Pontuacao --> GradeRedacao
  PontuacaoIA --> Competencia
  PontuacaoIA --> GradeRedacao
  Portaria --> Escola
  PreviaCarga --> Rede
  PreviaCargaEscola --> Escola
  PreviaCargaEscola --> PreviaCarga
  PreviaCargaPublico --> Pessoa
  PreviaCargaPublico --> PreviaCarga
  PreviaCargaPublico --> TwilioFilaEnvio
  Problema --> AlunoEscola
  Problema --> PerfilAcesso
  Problema --> MaterialDidaticoMonitoriaQuestao
  Problema --> Produto
  Problema --> PublicacaoCanal
  Problema --> Questao
  ProcessamentoBaseAvaliacoes --> RedeSerie
  ProcessamentoBoletim --> Escola
  ProcessamentoBoletim --> EscolaSerie
  ProcessamentoBoletim --> RedeSerie
  Produto --> ProdutoGrupo
  ProdutoPermissao --> AnoLetivo
  ProdutoPermissao --> Escola
  ProdutoPermissao --> PerfilAcesso
  ProdutoPermissao --> Produto
  ProdutoPermissao --> Rede
  ProdutoPermissao --> Serie
  ProdutoPermissao --> Turma
  Professor --> AnoLetivo
  Professor --> Pessoa
  Professor --> Rede
  Professor --> Segmento
  Professor --> TipoProfessor
  ProfessorCarga --> Disciplina
  ProfessorCarga --> MotivosSaida
  ProfessorCarga --> Pessoa
  ProfessorCarga --> ProfessorPerfilVigente
  ProfessorCarga --> Turma
  ProfessorCargaSubstituto --> MotivosSaida
  ProfessorCargaSubstituto --> Pessoa
  ProfessorCargaSubstituto --> ProfessorCarga
  ProfessorCargaSubstituto --> ProfessorPerfilVigente
  ProfessorChapa --> Cargo
  ProfessorChapa --> ProfessorPerfilVigente
  ProfessorChapaEscolaMes --> EscolaGerencial
  ProfessorChapaEscolaMes --> TipoDivisaoChapa
  ProfessorChapaEscolaMes --> AnoLetivo
  ProfessorChapaEscolaMes --> ProfessorChapa
  ProfessorClassePagamento --> AnoLetivo
  ProfessorClassePagamento --> ClassePagamento
  ProfessorClassePagamento --> ProfessorPerfilVigente
  ProfessorDisciplina --> Disciplina
  ProfessorDisciplina --> PessoaEscolaAcesso
  ProfessorHaPgto --> HoraAulaPgto
  ProfessorHaPgto --> Pessoa
  ProfessorHaSegmentoPgto --> HoraAulaSegmentoPgto
  ProfessorHaSegmentoPgto --> Pessoa
  ProfessorLicenca --> ProfessorPerfilVigente
  ProfessorLicenca --> SituacaoProfessor
  ProfessorLicencaTempos --> ProfessorLicenca
  ProfessorLicencaTempos --> Segmento
  ProfessorOcorrencia --> Escola
  ProfessorOcorrencia --> ProfessorOcorrenciaTipo
  ProfessorPerfilVigente --> Pessoa
  ProfessorPerfilVigente --> PessoaEscolaAcesso
  ProfessorPerfilVigente --> PessoaTelefone
  ProfessorPerfilVigente --> Rede
  ProfessorPerfilVigente --> Situacao
  ProfessorPerfilVigente --> SituacaoProfessor
  ProfessorTotalTempos --> AnoLetivo
  ProfessorTotalTempos --> Escola
  ProfessorTotalTempos --> ProfessorPerfilVigente
  ProfessorTurmaDisciplina --> Disciplina
  ProfessorTurmaDisciplina --> MotivosSaida
  ProfessorTurmaDisciplina --> PessoaEscolaAcesso
  ProfessorTurmaDisciplina --> Turma
  ProfessorTurmaDisciplina_Lixeira --> Disciplina
  ProfessorTurmaDisciplina_Lixeira --> PessoaEscolaAcesso
  ProfessorTurmaDisciplina_Lixeira --> Turma
  ProfessorTurmaDisciplinaCiclo --> EscolaSerieDisciplinaCiclo
  ProfessorTurmaDisciplinaCiclo --> Pessoa
  ProfessorTurmaDisciplinaCiclo --> Turma
  ProtocoloLancamento --> Avaliacao
  ProtocoloLancamento --> Chamada
  ProtocoloLancamento --> LogAcesso
  ProtocoloLancamento --> Turma
  ProtocoloLancamentoAluno --> Pessoa
  ProtocoloLancamentoAluno --> ProtocoloLancamento
  ProtocoloLancamentoAluno --> ProtocoloLancamentoStatus
  ProtocoloLancamentoBusca --> Agrupamento
  ProtocoloLancamentoBusca --> AnoLetivo
  ProtocoloLancamentoBusca --> Avaliacao
  ProtocoloLancamentoBusca --> Chamada
  ProtocoloLancamentoBusca --> Disciplina
  ProtocoloLancamentoBusca --> Escola
  ProtocoloLancamentoBusca --> Rede
  ProtocoloLancamentoBusca --> Turma
  Prova --> Agrupamento
  Prova --> Chamada
  Prova --> Ciclo
  Prova --> TipoAvaliacao
  Prova --> TipoCartaoResposta
  ProvaAvaliacao --> Avaliacao
  ProvaAvaliacao --> Prova
  ProvaAvaliacao --> TipoQuestao
  ProvaCodigo --> Prova
  ProvaCodigo --> ProvaModelo
  ProvaCodigo --> ProvaModeloCodigo
  ProvaCodigoAvaliacao --> ProvaAvaliacao
  ProvaCodigoAvaliacao --> ProvaCodigo
  ProvaCodigoAvaliacaoQuestao --> ProvaCodigoAvaliacao
  ProvaCodigoAvaliacaoQuestao --> Questao
  ProvaCodigoAvaliacaoQuestao --> TipoQuestao
  ProvaCodigoAvaliacaoQuestaoRevisao --> ProvaCodigoAvaliacaoQuestao
  ProvaCodigoAvaliacaoQuestaoRevisao --> Redacao
  ProvaCodigoAvaliacaoQuestaoRevisao --> RespostaRevisaoAvaliacao
  ProvaEditora --> Agrupamento
  ProvaEditora --> AnoLetivo
  ProvaEditora --> ParametroProvaEditora
  ProvaModelo --> Agrupamento
  ProvaModelo --> AnoLetivo
  ProvaModelo --> Ciclo
  ProvaModelo --> ProvaEditora
  ProvaModelo --> ProvaModelo
  ProvaModelo --> StatusProvaModelo
  ProvaModelo --> TipoAvaliacao
  ProvaModelo --> Turno
  ProvaModelo --> Usuario
  ProvaModeloCodigo --> ProvaModelo
  ProvaModeloCodigoQuestao --> ProvaModeloCodigo
  ProvaModeloCodigoQuestao --> Questao
  ProvaModeloConveniado --> Usuario
  ProvaModeloConveniadoQuestao --> ProvaModeloConveniado
  ProvaModeloConveniadoQuestao --> Questao
  ProvaModeloRede --> ProvaModelo
  ProvaModeloRede --> Rede
  ProvaTurma --> Prova
  ProvaTurma --> Turma
  PublicacaoCanal --> Assunto
  PublicacaoCanal --> Conteudo
  PublicacaoCanal --> Disciplina
  PublicacaoCanal --> PublicacaoCanalTipo
  PublicacaoCanalLIV --> Usuario
  PublicacaoCanalLIV --> ConteudoLIV
  PublicacaoCanalMaterialRelacionado --> Conteudo
  PublicacaoCanalMaterialRelacionado --> PublicacaoCanal
  PublicacaoCanalSerie --> PublicacaoCanal
  PublicacaoCanalSerie --> Serie
  Questao --> Conteudo
  Questao --> Questao
  QuestaoAutor --> AprovacaoQuestao
  QuestaoAutor --> Conteudo
  QuestaoAutor --> Questao
  QuestaoClassificacao --> Rede
  QuestaoClassificacao --> HabilidadeEnem
  QuestaoClassificacao --> PublicacaoCanal
  QuestaoClassificacao --> Segmento
  QuestaoClassificacao --> Assunto
  QuestaoClassificacao --> Disciplina
  QuestaoClassificacao --> HabilidadesBNCC
  QuestaoClassificacao --> HabilidadesENEM
  QuestaoClassificacao --> Questao
  QuestaoClassificacao --> QuestaoFonte
  QuestaoClassificacao --> QuestaoNivelDificuldade
  QuestaoClassificacao --> QuestaoStatus
  QuestaoClassificacao --> QuestaoTipo
  QuestaoClassificacao --> Tag
  QuestaoClassificacao --> Video
  QuestaoFeedback --> Origem
  QuestaoFeedback --> Questao
  QuestaoFeedback --> QuestaoTipoErro
  QuestaoLaplace --> Questao
  QuestaoLaplaceConsumida --> ConsumoQuestoesLaplace
  QuestaoLaplaceConsumidaErrosDeValidacao --> QuestaoLaplaceConsumida
  QuestaoOpcaoResposta --> Conteudo
  QuestaoOpcaoResposta --> Questao
  QuestaoRedeSerie --> Questao
  QuestaoRedeSerie --> Rede
  QuestaoRedeSerie --> Serie
  QuestaoRespostaDiscursiva --> Questao
  QuestaoRespostaObjetiva --> Questao
  QuestaoRespostaObjetivaMetrica --> QuestaoRespostaObjetiva
  QuestaoSimilar --> Questao
  QuestaoTag --> Questao
  QuestaoTag --> Tag
  Redacao --> Avaliacao
  Redacao --> Usuario
  Redacao --> EnvioLeituraCartao
  Redacao --> Redacao
  Redacao --> StatusRedacao
  Redacao --> AlunoCartao
  Redacao --> GradeRedacao
  RedacaoAvaliacaoCorrecaoIA --> AvaliacaoIA
  RedacaoAvaliacaoCorrecaoIA --> Redacao
  RedacaoCompetencia --> Competencia
  RedacaoCompetencia --> Redacao
  RedacaoCorrecaoIAAcompanhamento --> Redacao
  RedacaoCorrecaoIAAcompanhamento --> StatusCorrecaoIA
  RedacaoCorrecaoIAAcompanhamento --> TipoErroCorrecaoIA
  RedacaoDigital --> Pessoa
  RedacaoDigital --> ProvaAvaliacao
  RedacaoHistorico --> Redacao
  RedacaoHistorico --> StatusRedacao
  RedacaoHistoricoRevisaoIA --> Redacao
  RedacaoNotaCache --> Competencia
  RedacaoNotaCache --> Redacao
  RedacaoRegraGeral --> Redacao
  RedacaoRegraGeral --> RegraGeralRedacao
  RedacaoRevisao --> Redacao
  RedacaoRevisao --> StatusRedacaoRevisao
  RedacaoStatusHistorico --> Redacao
  Rede --> Rede
  Rede --> Periodo
  Rede --> Marca
  Rede --> TipoRede
  RedeAcesso --> Rede
  RedeIdioma --> Idioma
  RedeIdioma --> Rede
  RedeIntegracoes --> Rede
  RedeLivroDigital --> Rede
  RedeMaterialDidatico --> Rede
  RedeOpcao --> Opcao
  RedeOpcao --> Rede
  RedePagamentoRede --> Rede
  RedePagamentoRede --> RedePagamento
  RedeQuesito --> Quesito
  RedeQuesito --> Rede
  RedeSegmento --> Rede
  RedeSerie --> Agrupamento
  RedeSerie --> AnoLetivo
  RedeSerie --> Rede
  RedeSerie --> RedeSerie
  RedeSerie --> Serie
  RedeSerie --> ExtracaoBaseDeNotas
  RedeSerie --> TipoArredondamento
  RedeSerie --> TipoCalculo
  RedeSerieAgrupamento --> Agrupamento
  RedeSerieAgrupamento --> AnoLetivo
  RedeSerieAgrupamento --> Rede
  RedeSerieAgrupamento --> Serie
  RedeSerieCiclo --> Ciclo
  RedeSerieCiclo --> RedeSerie
  RedeSerieCicloAssunto --> Assunto
  RedeSerieCicloAssunto --> RedeSerieCiclo
  RedeSerieDisciplina --> AnoLetivo
  RedeSerieDisciplina --> Rede
  RedeSerieDisciplina --> AreaConhecimento
  RedeSerieDisciplina --> Disciplina
  RedeSerieDisciplina --> RedeSerie
  RedeSerieDisciplina --> RedeSerieDisciplina
  RedeSerieDisciplinaAssunto --> Assunto
  RedeSerieDisciplinaAssunto --> RedeSerieCiclo
  RedeSerieDisciplinaAssunto --> RedeSerieDisciplina
  RedeSerieDisciplinaCiclo --> RedeSerieCiclo
  RedeSerieDisciplinaCiclo --> RedeSerieDisciplina
  RedeSerieDisciplinaFrente --> Disciplina
  RedeSerieDisciplinaFrente --> RedeSerieDisciplina
  RedeSerieDisciplinaLinha --> RedeSerieDisciplina
  RedeSerieVersaoAnamnese --> RedeSerie
  RedeSerieVersaoAnamnese --> VersaoAnamnese
  RelatorioFolhaPeriodo --> AnoLetivo
  RelatorioFolhaPeriodo --> TipoRelatorioFolha
  RelatorioFolhaPublico --> AnoLetivo
  RelatorioFolhaPublico --> Rede
  RelatorioFolhaPublico --> TipoRelatorioFolha
  ReleaseNotes --> Funcionalidade
  ReleaseNotesVisualizacao --> ReleaseNotes
  RematriculaConveniados --> AlunoEscola
  RematriculaConveniados --> Turma
  ResponsavelAlunoClassroom --> AlunoEscola
  ResponsavelAlunoClassroom --> Pessoa
  ResponsavelAtendimento --> AlunoEscola
  ResponsavelAtendimento --> MotivoAtendimento
  ResponsavelAtendimento --> SolicitanteAtendimento
  RestricaoRankingSimuladoRede --> Rede
  RestricaoRankingSimuladoRede --> Simulado
  Resumo --> Assunto
  Resumo --> Disciplina
  Resumo --> Segmento
  Segmento --> Segmento
  SegmentoPagamento --> RedePagamento
  SegmentoSindical --> RedePagamento
  SemestreEletiva --> Serie
  Serie --> Agrupamento
  Serie --> CategoriaSerie
  Serie --> Curso
  Serie --> Escola
  Serie --> Serie
  Serie --> Segmento
  Serie --> SegmentoLIV
  SerieBolsao --> Serie
  SerieDePara --> Serie
  SerieDeParaImportacao --> Serie
  SerieDisciplinaPadrao --> AreaConhecimento
  SerieDisciplinaPadrao --> Serie
  SerieHisSerie --> HisSerie
  SerieHisSerie --> Serie
  SerieLaplaceAssociada --> Serie
  Series --> EscolaSerie
  Series --> PessoaEscolaAcesso
  ServicoCampoDinamico --> CampoDinamicoListaEspecifica
  ServicoCampoDinamico --> ChamadoOtrsTipo
  ServicoCampoDinamico --> CampoDinamico
  ServicoPerfilAcesso --> ChamadoOtrsTipo
  ServicoPerfilAcesso --> PerfilAcesso
  SimuladoAgrupamento --> Simulado
  SimuladoAgrupamento --> SimuladoTRI
  SimuladoQuestaoDetalhe --> CadernoProva
  SimuladoQuestaoDetalhe --> Simulado
  SimuladoTRI --> AnoLetivo
  SimuladoTRIAreaConhecimento --> AreaConhecimento
  SimuladoTRIAreaConhecimento --> SimuladoTRI
  SimuladoTRICalculo --> SimuladoTRI
  SimuladoTRIGabaritoOficial --> SimuladoTRI
  SimuladoTRIProvaCodigo --> ProvaCodigo
  SimuladoTRIProvaCodigo --> SimuladoTRI
  SimuladoTRIStatusCalculo --> SimuladoTRI
  SiteInstitucionalWhiteList --> Rede
  Situacao --> AnoLetivo
  Situacao --> Rede
  SolicitanteAtendimentoPorTipoRede --> SolicitanteAtendimento
  SolicitanteAtendimentoPorTipoRede --> TipoRede
  State --> Job
  StatusCovid --> Pessoa
  Tag --> Disciplina
  Tag --> Segmento
  Tag --> Tag
  Tags --> Conteudo
  Tags --> Tag
  TemplateEmail --> Rede
  TempoAula --> EscolaSerie
  TemporalMediasTCTRede --> Simulado
  TemporalMediasTCTUnidade --> Simulado
  TemporalNotasTRIEscola --> Escola
  TemporalNotasTRIEscola --> Simulado
  TemporalNotasTRIRede --> Rede
  TemporalNotasTRIRede --> Simulado
  TemporalQuestaoPercentual --> CadernoProva
  TemporalQuestaoPercentual --> Simulado
  TemporalRank --> Escola
  TemporalRank --> Pessoa
  TemporalRank --> Rede
  TemporalRank --> Turma
  TemporalRank --> Simulado
  TermosDeUsoRedePerfil --> PerfilAcesso
  TermosDeUsoRedePerfil --> TermosDeUso
  TermosDeUsoRedePerfil --> Rede
  Ticket --> Produto
  Ticket --> Usuario
  TicketProblemaMD --> MaterialDidaticoProblema
  TicketProblemaMD --> Usuario
  TipoAtendimentoPorTipoRede --> TipoAtendimento
  TipoAtendimentoPorTipoRede --> TipoRede
  TipoAulaOnlineRede --> Rede
  TipoAulaOnlineRede --> TipoAulaOnline
  TipoAulaOnlineRedeSerie --> RedeSerie
  TipoAulaOnlineRedeSerie --> TipoAulaOnline
  TipoAvaliacao --> AnoLetivo
  TipoAvaliacao --> TipoAvaliacao
  TipoAvaliacao --> Rede
  TipoAvaliacao --> TipoCartaoResposta
  TipoCartaoRespostaSomatorioAlternativa --> TipoCartaoResposta
  TipoCartaoRespostaSomatorioValor --> TipoCartaoResposta
  TipoComportamentoAluno --> Escola
  TipoComportamentoAluno --> Rede
  TipoComportamentoAlunoSerie --> Serie
  TipoComportamentoAlunoSerie --> TipoComportamentoAluno
  TipoComportamentoConfiguracao --> AnoLetivo
  TipoComportamentoConfiguracao --> Rede
  TipoComportamentoConfiguracao --> Segmento
  TipoComportamentoConfiguracao --> TipoComportamento
  TipoDocumento --> GrupoDocumento
  TipoEvento --> RedePagamento
  TipoEvento --> TipoEvento
  TipoEvento --> TipoPagamento
  TipoNotaFormativa --> GrupoNotaFormativa
  TipoNotaFormativa --> Rede
  TipoOcorrencia --> TipoOcorrencia
  TipoPublicoAtendidoPorTipoRede --> TipoPublicoAtendido
  TipoPublicoAtendidoPorTipoRede --> TipoRede
  TipoRedeFuncionalidadePadrao --> PerfilAcesso
  TipoRedeFuncionalidadePadrao --> Funcionalidade
  TipoRedeFuncionalidadePadrao --> TipoRede
  TipoRedeResultado --> TipoRede
  TipoRedeResultado --> TipoResultado
  TipoRedeSerie --> Serie
  TipoRedeSerie --> TipoRede
  TRI --> SimuladoTRI
  TRILinha --> TRI
  Turma --> Turma
  Turma --> Rede
  Turma --> RedeSegmento
  Turma --> EscolaSerie
  Turma --> Serie
  Turma --> TurmaClassroom
  Turma --> Turno
  TurmaAgrupada --> AnoLetivo
  TurmaAgrupada --> Disciplina
  TurmaAgrupada --> Rede
  TurmaAgrupada --> Serie
  TurmaAgrupadaTurma --> Turma
  TurmaAgrupadaTurma --> TurmaAgrupada
  TurmaClassroom --> TurmaAgrupada
  TurmaClassroom --> Disciplina
  TurmaClassroom --> Turma
  TurmaClassroomAtividade --> StatusAtividadeClassroom
  TurmaClassroomAtividade --> TurmaClassroom
  TurmaClassroomAtividadeAluno --> StatusAtividadeAlunoClassroom
  TurmaClassroomAtividadeAluno --> TurmaClassroomAtividade
  TurmaClassroomAtividadeDrive --> TurmaClassroomAtividade
  TurmaClassroomAtividadeForm --> TurmaClassroomAtividade
  TurmaClassroomAtividadeLink --> TurmaClassroomAtividade
  TurmaClassroomAtividadeYoutube --> TurmaClassroomAtividade
  TurmaClassroomPessoaEscolaAcesso --> Pessoa
  TurmaClassroomPessoaEscolaAcesso --> PessoaEscolaAcesso
  TurmaClassroomPessoaEscolaAcesso --> TurmaClassroom
  TurmaDisciplina --> Disciplina
  TurmaDisciplina --> Turma
  TurmaDisciplinaFolha --> DisciplinaFolha
  TurmaDisciplinaFolha --> Turma
  TurmaEletivaEscolaSerie --> EscolaSerie
  TurmaEletivaEscolaSerie --> Turma
  TurmaEscolaSerieDisciplina --> EscolaSerieDisciplina
  TurmaEscolaSerieDisciplina --> Turma
  TurmaHorarioPadrao --> Turma
  TurmaMacroTurma --> MacroTurma
  TurmaMacroTurma --> Turma
  TurmaTempo --> Turma
  TwilioFilaEnvio --> TwilioRemetente
  TwilioFilaEnvio --> TwilioTemplate
  TwilioFilaEnvioParametro --> TwilioFilaEnvio
  TwilioFilaEnvioParametro --> TwilioTemplateParametro
  TwilioRemetenteRede --> Rede
  TwilioRemetenteRede --> TwilioRemetente
  TwilioTemplate --> Funcionalidade
  TwilioTemplateParametro --> TwilioTemplate
  Usuario --> Idioma
  Usuario --> Pessoa
  UsuarioAcessoGuiaFinanceiro --> Rede
  UsuarioLinha --> Usuario
  UsuarioLIVConteudoLIV --> ConteudoLIV
  UsuarioProdutoDestaque --> Produto
  UsuarioUltimoFiltro --> UsuarioUltimoFiltro
  UsuarioVisualizouCampanha --> Campanha
  ValorPgtoProfessor --> MacroTurmaIntelpedTurma
  ValorPgtoProfessor --> ProfessorHaPgto
  ValorPgtoProfessorSegmento --> MacroTurmaIntelpedTurma
  ValorPgtoProfessorSegmento --> ProfessorHaSegmentoPgto
  VersaoAnamnesePadrao --> Segmento
  VersaoAnamnesePadrao --> TipoRede
  VersaoAnamnesePadrao --> VersaoAnamnese
  Video --> Assunto
  Video --> Disciplina
  Video --> VideoTipo
  'META FINAL$'
  'Tabelameta2019$'
  AggregatedCounter
  AgrupadorDeMeses
  AlocacaoFeriados
  AlocacaoProfessoresStatus
  AlunoAvaliacaoPresenca_bkp
  AlunoAvaliacaoPresenca_bkp2
  AlunoCartaoResposta
  AlunoEletivaModulo
  AlunoEscolaEleva2018
  AlunoEscolaEleva2018_05022018
  AlunoEscolaEnturmacaoTemp
  AlunoExecucaoProva2
  AlunoNotaEscolaEleva
  AlunoNota_bkp
  AlunoParaSincronizacao
  AlunoProvaMarcacao
  AlunoProvaQuestaoSomatorio
  AnoQuestao
  AtendimentoMeta2019
  AtendimentoTipoRelatorio
  Avatar
  BNCC
  BaseCanalEleva
  BaseDeAcessos
  BaseDeAtualidades
  BaseDeComprometimento
  BaseDeDesempenho
  BaseDeDesempenhoDisciplina
  BaseDeDisciplinas
  BaseDeDisciplinasParaLuppa
  BaseDeEletivasExcelencia
  BaseDeEsforcoResultado
  BaseDeLancamentoNotas
  BaseDeNotas
  BaseDeProfessoresParaLuppa
  BaseDeResponsaveis
  BaseDeSeriesPorAluno
  BaseDeSituacao
  BaseDeTRI
  BaseDeTurmas
  BaseDeUsuariosParaMarketing
  BaseDeUtilizacaoAlunos
  BaseDesempenhoPlataforma
  BaseEstrelasPlataforma
  BaseLivroDigital
  BaseMonitoriaOnline
  CabecalhoBoletim
  CalendarioEventoEntreguePorAluno
  CanalElevaControleAzureIndexer
  CaracteresInvalidosParaEmail
  CargaHorariaProfResumida
  CargaHorariaSubstituicoes
  CartaoValidacao
  ChamadoOtrsGrupo
  CombinacoesSimuladoSomatorio
  CombinacoesSimuladoSomatorioResultado
  Comentario
  ConfiguracaoAlocacao
  ConfiguracaoGlobalUsuario
  ConsultaBoletimAlunoCriptografado
  ConteudoVisualizacao
  ContratacaoPS
  ControleDeImportacaoDeAlunos
  ControleErroFotos
  ControleFotos
  ControleLinhasFotoTotvs
  Counter
  CustomClassroom
  DATAS
  DashboardEditora
  DeHabilitacaoParaSerie
  DisciplinaCargaHoraria
  DisciplinaLinha
  Disciplina_Origem
  Dummy
  EnturmacaoEE
  Escola_Origem
  EtapaDeResultadosSemelhante
  EventosProfessor
  FalhaLogin
  Feriado
  FiltroBaseDeDesempenho
  Fluig
  FonteQuestao
  FormaSolicitacaoPasse
  FormatoQuestao
  Handbook
  Hash
  HistoricoCargaProfessorEntrando
  HistoricoCargaProfessorSaindo
  HistoricoLiberacaoPedido
  HoraInicioFimPorTurma
  ImportTemp
  ImportTempEE
  ImportacaoAlunosEE
  ImportacaoAlunosGE
  ImportacaoAlunosTOTVS
  ImportacaoAlunosTOTVS_TurmasInvalidas
  ImportacaoClientesEscolaEleva
  ImportacaoClientesLog
  ImportacaoDependencias
  ImportacaoFrequencia
  ImportacaoLIVCoordenador
  ImportacaoLIVEscola
  ImportacaoLIVProfessor
  Importacao_Eletivas_Semestral
  IntegracaoEditora
  IntegralAlun
  IntencaoChatBot
  JobQueue
  Kiduca
  LIV_Aprovacao
  LIV_Feedback
  LIV_GoogleAuthData
  LIV_MigrationHistory
  LIV_MigrationHistorySeed
  LIV_TermosDeUso
  LIV_VideoLinks
  LinhaOrcamento
  List
  LogAcessoTipo
  LogAgenteImportacao
  LogAlteracaoEscolaAtivaAte
  LogAulaOnlineAssistida
  LogCadastroAluno
  LogClassificacaoQuestao
  LogDevolutivasHome
  LogEnturmacaoErro
  LogErrosPrevia
  LogEscolaAdimplente
  LogExecucao
  LogFluig
  LogFolha
  LogGoogleMeet
  LogImportacaoAlunos
  LogImportacaoPedidoEditora
  LogInconsistenciaImportacaoPedidoEditora
  LogMangaHigh
  LogProcessamentoBoletim
  LogRecuperacaoSenha
  LogRematricula
  LogTransferenciaAlunoComEletiva
  LogTrocaDeSenha
  MangaHigh
  Marca_Origem
  MaterialDidaticoClassificacaoMovimento
  MaterialDidaticoDeParaNaturezaFiscal
  MaterialDidaticoEscolaConfirmacaoEmail
  MaterialDidaticoEscolaPedidoAuxImportacao
  MaterialDidaticoImportacao
  MaterialDidaticoLocalSaida
  MaterialDidaticoProdutoTipo
  MaterialPlanejamentoPedagogico
  Mensageria
  MenuDevolutivas
  Meta permanência 2017'
  MonitorEscola
  NivelQuestao
  NotaElite
  NotaPensi
  Notificacao
  NotificacaoErroOtrs
  NovasFuncionalidadesId
  OTRSServiceIDs
  OperacaoGoogleMeet
  OrdenarTempos
  POAAlunoObservacoes
  POAAlunoObservacoes_Modulo
  POAAlunoOpcao_Modulo
  POAAluno_Modulo
  POAAvaliacaoResultado_Modulo
  POAAvaliacao_Modulo
  POANaoPossuiAula
  POANaoPossuiAula_Modulo
  POANaoSabeAvaliarProfessor_Modulo
  POAOpcao_Modulo
  POAPeriodoRede_Modulo
  POAPeriodo_Modulo
  POAPessoa_Modulo
  POAProfessor_Modulo
  POAQuesito_Modulo
  POATipoAplicacao_Modulo
  POATurma_Modulo
  PainelAluno
  ParamentrosSLA
  Parametro
  PercentualFrequenciaLog
  PeriodoCargaGoogleMeetRede
  PermissaoCartaoCredito
  PessoaEndereco
  PlanilhaLote
  PreviaCargaProfessores
  ProblemaStatus
  ProcessamentoDeTickets
  ProdutoTotvs
  ProfessorEscola
  ProvaCodigoArquivo
  ProvaOnline
  PublicoSerie
  QRCodeWhitelist
  QuestaoLaPlaceImportar
  RA_Maracaju_20180405
  RedacaoCompetencia_BKP
  RedacaoDigitalRegras
  Rede_Origem
  RegistrosImportacaoPedidoEditoraCSV
  RelacaoDisciplinaPlanejamentoPedagogico
  RelacaoSeriePlanejamentoPedagogico
  RelatorioAcessoFinanceiro
  RelatorioAlunoDesempenho
  RelatorioAlunoDesempenhoSimulados
  RelatorioAlunoNotaEE
  RelatorioAlunoUtilizacao
  RelatorioAlunoUtilizacaoCanalEleva
  RelatorioAlunoUtilizacaoMonitoriaOnline
  RelatorioComunicados
  RelatorioComunicadosLOG
  RelatorioFolha
  RelatorioLancamentoNotasEscolaEleva
  RelatorioLancamentoPresencas
  RelatorioPlataformaAdaptativa
  RelatorioPresencaEE
  RelatorioPresencaEmSimulados
  RelatorioPreviaCarga
  RelatorioSimulado
  RelatorioUploadCartoes
  RelatorioUploadCartoesAnalitico
  RotinasImportacao
  Sala
  Schema
  Segmento_Origem
  Serie_Origem
  Server
  ServicosCamposDinamicosOTRS
  ServicosContratadosTipoRelatorio
  Set
  SimuladoDetalhe
  SituacaoQuestoesLaplace
  StatusBoletim
  StatusControleEmail
  StatusLancamentoFrequencia
  StatusQuestao
  TEMP_DBA_JHY
  TempAlunoEscolaRestore
  TempAlunosSaes
  TempArquivoFileServerDelete
  TempImportacaoAlunos
  TempLogUpdateUsuario
  TempPessoaEscolaAcessoRestore
  TempPessoaEscolaRestore
  TempServerIPLog
  TipoDisciplina
  TipoEspacamento
  TipoFarol
  TipoModal
  TipoSanguineo
  TipoSituacaoBinaria
  ToDoTarefa
  Turma_Origem
  TurmasBarraPOA2019
  TurmasBotafogoPOA2019
  TurmasIgnoradas
  UnidadesEscolasGeCalc
  UsuarioAcesso
  UsuarioAcessoGuia
  UsuarioAuthToken
  UsuarioEscolaEleva
  UsuarioFuncionalidade
  UsuarioLIV
  UsuarioLogarComo
  UsuarioRede
  UsuarioSismat
  UsuarioVisualizouRegraPLAD
  Usuario_Origem
  Usuario_id_origem
  UsuariosNotificacaoEnvioCartao
  ValidacaoDeBoletim
  VersionInfo
  _DELETEME_TempEnem1
  _DELETEME_TempRankEnem1
  _MigrationHistory
  bkp_email_usuario
  dummy
  logAlunoNota
  logclassroom
  segmentoProfessor
  sysdiagrams
  tempEmailEnviados
  temp_BasicAcessouUltimosMeses
  temp_EnvioLeitura
  tmpCargaAluno
